export type MockSystem = {
  id: string;
  name: string;
  slug: string;
  description: string;
  deploymentCount: number;
  environmentCount: number;
  resourceCount: number;
  activeDeployments: number;
  lastDeployment: string;
  status: "healthy" | "degraded" | "warning";
  owner: string;
  tags: string[];
};

export const mockSystems: MockSystem[] = [
  {
    id: "sys-1",
    name: "E-commerce Platform",
    slug: "ecommerce-platform",
    description:
      "Main customer-facing e-commerce application with shopping cart, checkout, and order management",
    deploymentCount: 8,
    environmentCount: 6,
    resourceCount: 45,
    activeDeployments: 24,
    lastDeployment: "5 minutes ago",
    status: "healthy",
    owner: "Sarah Chen",
    tags: ["production", "customer-facing", "critical"],
  },
  {
    id: "sys-2",
    name: "Payment Service",
    slug: "payment-service",
    description:
      "Secure payment processing, transaction management, and fraud detection system",
    deploymentCount: 5,
    environmentCount: 4,
    resourceCount: 28,
    activeDeployments: 15,
    lastDeployment: "15 minutes ago",
    status: "healthy",
    owner: "Michael Johnson",
    tags: ["payment", "security", "pci-compliant"],
  },
  {
    id: "sys-3",
    name: "Analytics Pipeline",
    slug: "analytics-pipeline",
    description:
      "Real-time data processing and analytics platform for business intelligence and reporting",
    deploymentCount: 12,
    environmentCount: 5,
    resourceCount: 62,
    activeDeployments: 36,
    lastDeployment: "25 minutes ago",
    status: "warning",
    owner: "Emily Rodriguez",
    tags: ["analytics", "big-data", "real-time"],
  },
  {
    id: "sys-4",
    name: "Authentication Service",
    slug: "auth-service",
    description:
      "Centralized SSO, OAuth2, and identity management service for all applications",
    deploymentCount: 3,
    environmentCount: 5,
    resourceCount: 18,
    activeDeployments: 10,
    lastDeployment: "20 minutes ago",
    status: "healthy",
    owner: "Robert Chen",
    tags: ["auth", "security", "sso"],
  },
  {
    id: "sys-5",
    name: "Notification Service",
    slug: "notification-service",
    description:
      "Multi-channel notification platform for email, SMS, push notifications, and webhooks",
    deploymentCount: 4,
    environmentCount: 4,
    resourceCount: 22,
    activeDeployments: 9,
    lastDeployment: "35 minutes ago",
    status: "healthy",
    owner: "Jessica Brown",
    tags: ["notifications", "messaging", "communication"],
  },
  {
    id: "sys-6",
    name: "Inventory Management",
    slug: "inventory-management",
    description:
      "Warehouse management, stock tracking, and supply chain optimization system",
    deploymentCount: 6,
    environmentCount: 4,
    resourceCount: 32,
    activeDeployments: 14,
    lastDeployment: "45 minutes ago",
    status: "healthy",
    owner: "James Martinez",
    tags: ["inventory", "warehouse", "logistics"],
  },
  {
    id: "sys-7",
    name: "Customer Support Platform",
    slug: "support-platform",
    description:
      "Ticketing system, live chat, knowledge base, and customer relationship management",
    deploymentCount: 5,
    environmentCount: 3,
    resourceCount: 25,
    activeDeployments: 9,
    lastDeployment: "2 hours ago",
    status: "healthy",
    owner: "Lisa Wang",
    tags: ["support", "crm", "customer-service"],
  },
  {
    id: "sys-8",
    name: "Content Management System",
    slug: "cms",
    description:
      "Headless CMS for managing website content, blog posts, and marketing materials",
    deploymentCount: 3,
    environmentCount: 3,
    resourceCount: 15,
    activeDeployments: 7,
    lastDeployment: "1 day ago",
    status: "healthy",
    owner: "Jennifer Park",
    tags: ["cms", "content", "marketing"],
  },
  {
    id: "sys-9",
    name: "Search Engine",
    slug: "search-engine",
    description:
      "Elasticsearch-based search indexing and query service with autocomplete and fuzzy matching",
    deploymentCount: 4,
    environmentCount: 4,
    resourceCount: 24,
    activeDeployments: 13,
    lastDeployment: "50 minutes ago",
    status: "healthy",
    owner: "Thomas Wilson",
    tags: ["search", "elasticsearch", "indexing"],
  },
  {
    id: "sys-10",
    name: "Mobile API Gateway",
    slug: "mobile-api",
    description:
      "REST and GraphQL API gateway for iOS and Android mobile applications",
    deploymentCount: 6,
    environmentCount: 5,
    resourceCount: 35,
    activeDeployments: 18,
    lastDeployment: "30 minutes ago",
    status: "healthy",
    owner: "David Kim",
    tags: ["mobile", "api", "gateway"],
  },
  {
    id: "sys-11",
    name: "Data Lake Storage",
    slug: "data-lake",
    description:
      "Scalable data storage and retrieval system for raw and processed data",
    deploymentCount: 7,
    environmentCount: 4,
    resourceCount: 40,
    activeDeployments: 16,
    lastDeployment: "10 minutes ago",
    status: "degraded",
    owner: "Kevin Thompson",
    tags: ["data", "storage", "data-lake"],
  },
  {
    id: "sys-12",
    name: "IoT Device Management",
    slug: "iot-platform",
    description:
      "Device registration, telemetry collection, and remote control for IoT devices",
    deploymentCount: 8,
    environmentCount: 5,
    resourceCount: 48,
    activeDeployments: 20,
    lastDeployment: "25 minutes ago",
    status: "healthy",
    owner: "Daniel Lee",
    tags: ["iot", "devices", "telemetry"],
  },
  {
    id: "sys-13",
    name: "Machine Learning Pipeline",
    slug: "ml-pipeline",
    description:
      "Model training, inference, and deployment pipeline for AI/ML workloads",
    deploymentCount: 5,
    environmentCount: 4,
    resourceCount: 30,
    activeDeployments: 11,
    lastDeployment: "1 hour ago",
    status: "healthy",
    owner: "Maria Garcia",
    tags: ["ml", "ai", "training"],
  },
  {
    id: "sys-14",
    name: "Video Streaming",
    slug: "video-streaming",
    description:
      "Video encoding, storage, CDN distribution, and adaptive streaming service",
    deploymentCount: 9,
    environmentCount: 5,
    resourceCount: 55,
    activeDeployments: 22,
    lastDeployment: "15 minutes ago",
    status: "healthy",
    owner: "Rachel Green",
    tags: ["video", "streaming", "media"],
  },
  {
    id: "sys-15",
    name: "Admin Dashboard",
    slug: "admin-dashboard",
    description:
      "Internal tools and administrative interface for operations and customer service teams",
    deploymentCount: 4,
    environmentCount: 2,
    resourceCount: 12,
    activeDeployments: 4,
    lastDeployment: "4 hours ago",
    status: "healthy",
    owner: "Chris Anderson",
    tags: ["admin", "internal", "tools"],
  },
  {
    id: "sys-16",
    name: "Marketing Automation",
    slug: "marketing-automation",
    description:
      "Email campaigns, A/B testing, lead scoring, and marketing analytics platform",
    deploymentCount: 5,
    environmentCount: 3,
    resourceCount: 20,
    activeDeployments: 8,
    lastDeployment: "3 hours ago",
    status: "healthy",
    owner: "Amanda Foster",
    tags: ["marketing", "automation", "campaigns"],
  },
  {
    id: "sys-17",
    name: "API Rate Limiter",
    slug: "rate-limiter",
    description:
      "Distributed rate limiting and throttling service for API protection",
    deploymentCount: 3,
    environmentCount: 4,
    resourceCount: 16,
    activeDeployments: 10,
    lastDeployment: "1 hour ago",
    status: "healthy",
    owner: "Alex Turner",
    tags: ["api", "security", "rate-limiting"],
  },
  {
    id: "sys-18",
    name: "Recommendation Engine",
    slug: "recommendation-engine",
    description:
      "Collaborative filtering and machine learning-based product recommendation system",
    deploymentCount: 4,
    environmentCount: 4,
    resourceCount: 26,
    activeDeployments: 11,
    lastDeployment: "1 hour ago",
    status: "healthy",
    owner: "Maria Garcia",
    tags: ["recommendations", "ml", "personalization"],
  },
];
