packages:
  - e2e
  - apps/*
  - packages/*
  - tooling/*
  - integrations/*

catalog:
  '@hookform/resolvers': 3.10.0
  '@octokit/auth-app': ^7.1.5
  '@octokit/rest': ^20.1.1
  '@t3-oss/env-core': 0.11.1
  '@tabler/icons-react': ^3.31.0
  '@types/lodash': ^4.17.21
  '@types/ms': ^0.7.34
  date-fns: 3.6.0
  dotenv-cli: ^7.4.4
  eslint: 9.11.1
  eslint-plugin-vitest: ^0.5.4
  lodash: ^4.17.21
  ms: ^2.1.3
  prettier: ^3.7.4
  react-hook-form: 7.54.2
  semver: ^7.7.1
  superjson: ^2.2.2
  tailwindcss: 3.4.17
  ts-is-present: ^1.2.2
  tsx: ^4.19.1
  typescript: ^5.8.2
  typescript-eslint: ^8.13.0
  zod: 3.24.2

catalogs:
  node22:
    '@types/node': ^22.5.5
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: 19.2.1
    react-dom: 19.2.1
  tailwindcssv4:
    tailwind-scrollbar: ^4.0.2
    tailwindcss: ^4.1.14
  zod3:
    zod: 3.24.2
  zod4:
    zod: 4.1.12

overrides:
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0

peerDependencyRules:
  allowAny:
    - '*'
