packages:
  - apps/*
  - packages/*
  - tooling/*
  - integrations/*

catalog:
  eslint: ^9.11.1
  eslint-plugin-vitest: ^0.5.4
  typescript-eslint: ^8.13.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.11
  typescript: ^5.8.2
  zod: ^3.23.8
  "@t3-oss/env-core": ^0.11.1
  "@t3-oss/env-nextjs": ^0.11.1
  "date-fns": ^3.6.0
  "@octokit/rest": ^20.1.1
  "tsx": ^4.19.1
  "lodash": ^4.17.21
  "@types/lodash": ^4.17.5
  "next": ^14.2.17
  "next-auth": "5.0.0-beta.25"
  "@next/eslint-plugin-next": ^14.2.6
  "bullmq": ^5.15.0
  "ts-is-present": ^1.2.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.5
    "@types/react-dom": ^18.3.0
  node22:
    "@types/node": ^22.5.5
  node20:
    "@types/node": ^20.12.0
