packages:
  - e2e
  - apps/*
  - packages/*
  - tooling/*
  - integrations/*

catalog:
  '@hookform/resolvers': ^3.10.0
  '@next/eslint-plugin-next': ^15.2.2
  '@octokit/auth-app': ^7.1.5
  '@octokit/rest': ^20.1.1
  '@t3-oss/env-core': ^0.11.1
  '@t3-oss/env-nextjs': ^0.11.1
  '@tabler/icons-react': ^3.31.0
  '@types/lodash': ^4.17.5
  '@types/ms': ^0.7.34
  bullmq: ^5.48.1
  date-fns: ^3.6.0
  dotenv-cli: ^7.4.4
  eslint: 9.11.1
  eslint-plugin-vitest: ^0.5.4
  ioredis: ^5.4.1
  lodash: ^4.17.21
  ms: ^2.1.3
  next: 15.2.1
  next-auth: 5.0.0-beta.25
  prettier: ^3.5.3
  react-hook-form: ^7.54.2
  redis-semaphore: ^5.6.2
  semver: ^7.7.1
  superjson: ^2.2.2
  tailwindcss: ^3.4.17
  ts-is-present: ^1.2.2
  tsx: ^4.19.1
  typescript: ^5.8.2
  typescript-eslint: ^8.13.0
  zod: 3.24.2

catalogs:
  node20:
    '@types/node': ^20.12.0
  node22:
    '@types/node': ^22.5.5
  react18:
    '@types/react': ^18.3.5
    '@types/react-dom': ^18.3.0
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0
    react: 19.0.0
    react-dom: 19.0.0
