packages:
  - apps/*
  - packages/*
  - tooling/*
  - agents/*
  - providers/*

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
