version: "2"
linters:
  disable:
    - errcheck
  enable:
    # - tagliatelle
    # - nilerr
    # - govet
    # - nestif
    - copyloopvar
    - iface
    - fatcontext
    # - nilnil
    - godot
    - gocritic
    - mirror
    - tagalign
    # - predeclared
    # - gosec
    # - interfacebloat
    - intrange
    # - iotamixing
    # - maintidx
    - modernize
    # - paralleltest
    - testifylint
    # - thelper
    # - unconvert
    - unqueryvet
    - unused
    - usestdlibvars
    - asciicheck
    - bidichk
  settings:
    interfacebloat:
      max: 5
    tagliatelle:
      case:
        rules:
          # yaml: camel
          envconfig: upperSnake

formatters:
  enable:
    - gofmt
    - golines
    - gci
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
