import type { DeploymentDetail, Environment } from "./types";

export const mockEnvironments: Environment[] = [
  {
    id: "env1",
    name: "production",
    description: "Production environment",
    policies: [],
    dependsOnEnvironmentIds: ["env2"],
  },
  {
    id: "env2",
    name: "staging",
    description: "Staging environment for testing",
    policies: [],
    dependsOnEnvironmentIds: ["env3"],
  },
  {
    id: "env3",
    name: "dev-pr-123",
    description: "Development environment for PR #123",
    policies: [],
    dependsOnEnvironmentIds: [],
  },
  {
    id: "env4",
    name: "dev-pr-456",
    description: "Development environment for PR #456",
    policies: [],
    dependsOnEnvironmentIds: [],
  },
  {
    id: "env5",
    name: "dev-pr-789",
    description: "Development environment for PR #789",
    policies: [],
    dependsOnEnvironmentIds: [],
  },
];

export const mockDeploymentDetail: DeploymentDetail = {
  id: "1",
  name: "frontend-api",
  slug: "frontend-api",
  description: "Main frontend API service handling user requests",
  systemId: "sys-1",
  systemName: "E-commerce Platform",
  environments: mockEnvironments,
  versions: [
    {
      id: "v1",
      name: "Release 1.24.5",
      tag: "v1.24.5",
      status: "ready",
      createdAt: "2 minutes ago",
      message: "fix: update checkout flow validation",
      releaseTargetCount: 12,
      environmentCount: 3,
      currentEnvironments: ["production", "staging", "dev-pr-123"],
    },
    {
      id: "v2",
      name: "Release 1.24.4",
      tag: "v1.24.4",
      status: "ready",
      createdAt: "15 minutes ago",
      message: "feat: add new payment gateway integration",
      releaseTargetCount: 8,
      environmentCount: 2,
      currentEnvironments: ["staging", "dev-pr-456"],
    },
    {
      id: "v3",
      name: "Release 1.24.3",
      tag: "v1.24.3",
      status: "building",
      createdAt: "28 minutes ago",
      message: "chore: update dependencies to latest versions",
      releaseTargetCount: 4,
      environmentCount: 1,
      currentEnvironments: ["dev-pr-789"],
    },
    {
      id: "v4",
      name: "Release 1.24.2",
      tag: "v1.24.2",
      status: "ready",
      createdAt: "45 minutes ago",
      message: "fix: cart calculation rounding error",
      releaseTargetCount: 5,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v5",
      name: "Release 1.24.1",
      tag: "v1.24.1",
      status: "ready",
      createdAt: "1 hour ago",
      message: "perf: optimize database queries",
      releaseTargetCount: 0,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v6",
      name: "Release 1.24.0",
      tag: "v1.24.0",
      status: "ready",
      createdAt: "2 hours ago",
      message: "feat: multi-currency support",
      releaseTargetCount: 0,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v7",
      name: "Release 1.23.9",
      tag: "v1.23.9",
      status: "failed",
      createdAt: "3 hours ago",
      message: "fix: session timeout issue",
      releaseTargetCount: 0,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v8",
      name: "Release 1.23.8",
      tag: "v1.23.8",
      status: "ready",
      createdAt: "4 hours ago",
      message: "docs: update API documentation",
      releaseTargetCount: 8,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v9",
      name: "Release 1.23.7",
      tag: "v1.23.7",
      status: "ready",
      createdAt: "5 hours ago",
      message: "feat: add wishlist functionality",
      releaseTargetCount: 7,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v10",
      name: "Release 1.23.6",
      tag: "v1.23.6",
      status: "ready",
      createdAt: "6 hours ago",
      message: "fix: mobile responsive layout",
      releaseTargetCount: 9,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v11",
      name: "Release 1.23.5",
      tag: "v1.23.5",
      status: "rejected",
      createdAt: "7 hours ago",
      message: "feat: experimental feature flag",
      releaseTargetCount: 0,
      environmentCount: 0,
      currentEnvironments: [],
    },
    {
      id: "v12",
      name: "Release 1.23.4",
      tag: "v1.23.4",
      status: "ready",
      createdAt: "8 hours ago",
      message: "fix: memory leak in websocket",
      releaseTargetCount: 11,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v13",
      name: "Release 1.23.3",
      tag: "v1.23.3",
      status: "ready",
      createdAt: "9 hours ago",
      message: "chore: upgrade React to v19",
      releaseTargetCount: 8,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v14",
      name: "Release 1.23.2",
      tag: "v1.23.2",
      status: "ready",
      createdAt: "10 hours ago",
      message: "feat: dark mode support",
      releaseTargetCount: 10,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v15",
      name: "Release 1.23.1",
      tag: "v1.23.1",
      status: "ready",
      createdAt: "11 hours ago",
      message: "fix: authentication token refresh",
      releaseTargetCount: 7,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v16",
      name: "Release 1.23.0",
      tag: "v1.23.0",
      status: "ready",
      createdAt: "12 hours ago",
      message: "feat: implement GraphQL API",
      releaseTargetCount: 12,
      environmentCount: 4,
      currentEnvironments: [],
    },
    {
      id: "v17",
      name: "Release 1.22.8",
      tag: "v1.22.8",
      status: "ready",
      createdAt: "14 hours ago",
      message: "fix: handle edge cases in search",
      releaseTargetCount: 6,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v18",
      name: "Release 1.22.7",
      tag: "v1.22.7",
      status: "failed",
      createdAt: "15 hours ago",
      message: "perf: lazy loading images",
      releaseTargetCount: 1,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v19",
      name: "Release 1.22.6",
      tag: "v1.22.6",
      status: "ready",
      createdAt: "16 hours ago",
      message: "feat: email notification preferences",
      releaseTargetCount: 9,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v20",
      name: "Release 1.22.5",
      tag: "v1.22.5",
      status: "ready",
      createdAt: "18 hours ago",
      message: "fix: CORS configuration",
      releaseTargetCount: 5,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v21",
      name: "Release 1.22.4",
      tag: "v1.22.4",
      status: "ready",
      createdAt: "20 hours ago",
      message: "chore: cleanup unused code",
      releaseTargetCount: 8,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v22",
      name: "Release 1.22.3",
      tag: "v1.22.3",
      status: "ready",
      createdAt: "22 hours ago",
      message: "feat: advanced filtering options",
      releaseTargetCount: 7,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v23",
      name: "Release 1.22.2",
      tag: "v1.22.2",
      status: "ready",
      createdAt: "1 day ago",
      message: "fix: timezone handling",
      releaseTargetCount: 4,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v24",
      name: "Release 1.22.1",
      tag: "v1.22.1",
      status: "ready",
      createdAt: "1 day ago",
      message: "docs: add deployment guide",
      releaseTargetCount: 3,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v25",
      name: "Release 1.22.0",
      tag: "v1.22.0",
      status: "ready",
      createdAt: "1 day ago",
      message: "feat: SSO integration",
      releaseTargetCount: 10,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v26",
      name: "Release 1.21.9",
      tag: "v1.21.9",
      status: "ready",
      createdAt: "1 day ago",
      message: "fix: rate limiting middleware",
      releaseTargetCount: 6,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v27",
      name: "Release 1.21.8",
      tag: "v1.21.8",
      status: "ready",
      createdAt: "2 days ago",
      message: "perf: cache API responses",
      releaseTargetCount: 5,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v28",
      name: "Release 1.21.7",
      tag: "v1.21.7",
      status: "ready",
      createdAt: "2 days ago",
      message: "feat: export to CSV",
      releaseTargetCount: 4,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v29",
      name: "Release 1.21.6",
      tag: "v1.21.6",
      status: "failed",
      createdAt: "2 days ago",
      message: "fix: file upload size limit",
      releaseTargetCount: 0,
      environmentCount: 0,
      currentEnvironments: [],
    },
    {
      id: "v30",
      name: "Release 1.21.5",
      tag: "v1.21.5",
      status: "ready",
      createdAt: "2 days ago",
      message: "chore: update CI/CD pipeline",
      releaseTargetCount: 8,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v31",
      name: "Release 1.21.4",
      tag: "v1.21.4",
      status: "ready",
      createdAt: "3 days ago",
      message: "feat: analytics dashboard",
      releaseTargetCount: 7,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v32",
      name: "Release 1.21.3",
      tag: "v1.21.3",
      status: "ready",
      createdAt: "3 days ago",
      message: "fix: XSS vulnerability patch",
      releaseTargetCount: 12,
      environmentCount: 4,
      currentEnvironments: [],
    },
    {
      id: "v33",
      name: "Release 1.21.2",
      tag: "v1.21.2",
      status: "ready",
      createdAt: "3 days ago",
      message: "feat: bulk operations",
      releaseTargetCount: 6,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v34",
      name: "Release 1.21.1",
      tag: "v1.21.1",
      status: "ready",
      createdAt: "3 days ago",
      message: "fix: pagination bug",
      releaseTargetCount: 3,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v35",
      name: "Release 1.21.0",
      tag: "v1.21.0",
      status: "ready",
      createdAt: "4 days ago",
      message: "feat: real-time notifications",
      releaseTargetCount: 11,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v36",
      name: "Release 1.20.8",
      tag: "v1.20.8",
      status: "ready",
      createdAt: "4 days ago",
      message: "fix: email template rendering",
      releaseTargetCount: 5,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v37",
      name: "Release 1.20.7",
      tag: "v1.20.7",
      status: "ready",
      createdAt: "4 days ago",
      message: "perf: optimize bundle size",
      releaseTargetCount: 9,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v38",
      name: "Release 1.20.6",
      tag: "v1.20.6",
      status: "ready",
      createdAt: "5 days ago",
      message: "feat: two-factor authentication",
      releaseTargetCount: 10,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v39",
      name: "Release 1.20.5",
      tag: "v1.20.5",
      status: "ready",
      createdAt: "5 days ago",
      message: "fix: API error handling",
      releaseTargetCount: 4,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v40",
      name: "Release 1.20.4",
      tag: "v1.20.4",
      status: "rejected",
      createdAt: "5 days ago",
      message: "test: experimental A/B test",
      releaseTargetCount: 0,
      environmentCount: 0,
      currentEnvironments: [],
    },
    {
      id: "v41",
      name: "Release 1.20.3",
      tag: "v1.20.3",
      status: "ready",
      createdAt: "6 days ago",
      message: "chore: security audit fixes",
      releaseTargetCount: 8,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v42",
      name: "Release 1.20.2",
      tag: "v1.20.2",
      status: "ready",
      createdAt: "6 days ago",
      message: "feat: keyboard shortcuts",
      releaseTargetCount: 6,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v43",
      name: "Release 1.20.1",
      tag: "v1.20.1",
      status: "ready",
      createdAt: "6 days ago",
      message: "fix: mobile navigation",
      releaseTargetCount: 3,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v44",
      name: "Release 1.20.0",
      tag: "v1.20.0",
      status: "ready",
      createdAt: "1 week ago",
      message: "feat: redesigned UI components",
      releaseTargetCount: 12,
      environmentCount: 4,
      currentEnvironments: [],
    },
    {
      id: "v45",
      name: "Release 1.19.9",
      tag: "v1.19.9",
      status: "ready",
      createdAt: "1 week ago",
      message: "fix: websocket reconnection",
      releaseTargetCount: 7,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v46",
      name: "Release 1.19.8",
      tag: "v1.19.8",
      status: "ready",
      createdAt: "1 week ago",
      message: "perf: reduce API latency",
      releaseTargetCount: 9,
      environmentCount: 3,
      currentEnvironments: [],
    },
    {
      id: "v47",
      name: "Release 1.19.7",
      tag: "v1.19.7",
      status: "ready",
      createdAt: "1 week ago",
      message: "feat: customizable themes",
      releaseTargetCount: 5,
      environmentCount: 2,
      currentEnvironments: [],
    },
    {
      id: "v48",
      name: "Release 1.19.6",
      tag: "v1.19.6",
      status: "failed",
      createdAt: "1 week ago",
      message: "fix: database migration rollback",
      releaseTargetCount: 0,
      environmentCount: 0,
      currentEnvironments: [],
    },
    {
      id: "v49",
      name: "Release 1.19.5",
      tag: "v1.19.5",
      status: "ready",
      createdAt: "1 week ago",
      message: "chore: update license",
      releaseTargetCount: 2,
      environmentCount: 1,
      currentEnvironments: [],
    },
    {
      id: "v50",
      name: "Release 1.19.4",
      tag: "v1.19.4",
      status: "ready",
      createdAt: "2 weeks ago",
      message: "feat: audit logging system",
      releaseTargetCount: 4,
      environmentCount: 2,
      currentEnvironments: [],
    },
  ],
  releaseTargets: [
    {
      environment: { id: "env1", name: "production" },
      resource: {
        id: "r1",
        name: "api-prod-1",
        kind: "kubernetes-deployment",
        identifier: "k8s://prod/api-prod-1",
      },
      version: {
        currentId: "v1",
        desiredId: "v1", // Latest, all policies passed
      },
      jobs: [
        {
          id: "j1",
          status: "successful",
          createdAt: "2 minutes ago",
          startedAt: "2 minutes ago",
          completedAt: "1 minute ago",
        },
      ],
    },
    {
      environment: { id: "env1", name: "production" },
      resource: {
        id: "r2",
        name: "api-prod-2",
        kind: "kubernetes-deployment",
        identifier: "k8s://prod/api-prod-2",
      },
      version: {
        currentId: "v2",
        desiredId: "v1", // Can update to v1 (canary rollout in progress)
      },
      jobs: [
        {
          id: "j2",
          status: "inProgress",
          createdAt: "1 minute ago",
          startedAt: "30 seconds ago",
        },
      ],
    },
    {
      environment: { id: "env1", name: "production" },
      resource: {
        id: "r3",
        name: "api-prod-3",
        kind: "kubernetes-deployment",
        identifier: "k8s://prod/api-prod-3",
      },
      version: {
        currentId: "v3",
        desiredId: "v2", // Can only update to v2, v1 is blocked
        blockedVersions: [
          {
            versionId: "v1",
            reason: "Approval required from security team",
          },
        ],
      },
      jobs: [
        {
          id: "j3",
          status: "successful",
          createdAt: "15 minutes ago",
          startedAt: "15 minutes ago",
          completedAt: "14 minutes ago",
        },
      ],
    },
    {
      environment: { id: "env1", name: "production" },
      resource: {
        id: "r4",
        name: "api-prod-4",
        kind: "kubernetes-deployment",
        identifier: "k8s://prod/api-prod-4",
      },
      version: {
        currentId: "v4",
        desiredId: "v4", // Stuck on old version, multiple versions blocked
        blockedVersions: [
          {
            versionId: "v1",
            reason: "Requires approval",
          },
          {
            versionId: "v2",
            reason: "Environment progression rule not met",
          },
          {
            versionId: "v3",
            reason: "Deployment window restriction",
          },
        ],
      },
      jobs: [
        {
          id: "j4",
          status: "successful",
          createdAt: "2 hours ago",
          startedAt: "2 hours ago",
          completedAt: "2 hours ago",
        },
      ],
    },
    {
      environment: { id: "env2", name: "staging" },
      resource: {
        id: "r7",
        name: "api-staging-1",
        kind: "kubernetes-deployment",
        identifier: "k8s://staging/api-staging-1",
      },
      version: {
        currentId: "v2",
        desiredId: "v1", // Updating to v1.24.5
      },
      jobs: [
        {
          id: "j7",
          status: "inProgress",
          createdAt: "1 minute ago",
          startedAt: "30 seconds ago",
        },
      ],
    },
    {
      environment: { id: "env2", name: "staging" },
      resource: {
        id: "r8",
        name: "api-staging-2",
        kind: "kubernetes-deployment",
        identifier: "k8s://staging/api-staging-2",
      },
      version: {
        currentId: "v3",
        desiredId: "v2", // Different desired version! (gradual rollout)
      },
      jobs: [
        {
          id: "j8",
          status: "inProgress",
          createdAt: "2 minutes ago",
          startedAt: "1 minute ago",
        },
      ],
    },
    {
      environment: { id: "env2", name: "staging" },
      resource: {
        id: "r9",
        name: "api-staging-3",
        kind: "kubernetes-deployment",
        identifier: "k8s://staging/api-staging-3",
      },
      version: {
        currentId: "v4",
        desiredId: "v1", // Skipping v2, v3, going straight to v1
      },
      jobs: [
        {
          id: "j9",
          status: "pending",
          createdAt: "30 seconds ago",
        },
      ],
    },
    {
      environment: { id: "env3", name: "dev-pr-123" },
      resource: {
        id: "r4",
        name: "api-dev-pr-123",
        kind: "kubernetes-deployment",
        identifier: "k8s://dev/api-dev-pr-123",
      },
      version: {
        currentId: "v1",
        desiredId: "v1",
      },
      jobs: [
        {
          id: "j4",
          status: "successful",
          createdAt: "5 minutes ago",
          startedAt: "5 minutes ago",
          completedAt: "4 minutes ago",
        },
      ],
    },
    {
      environment: { id: "env4", name: "dev-pr-456" },
      resource: {
        id: "r5",
        name: "api-dev-pr-456",
        kind: "kubernetes-deployment",
        identifier: "k8s://dev/api-dev-pr-456",
      },
      version: {
        currentId: "v2",
        desiredId: "v2",
      },
      jobs: [
        {
          id: "j5",
          status: "successful",
          createdAt: "10 minutes ago",
          startedAt: "10 minutes ago",
          completedAt: "9 minutes ago",
        },
      ],
    },
    {
      environment: { id: "env5", name: "dev-pr-789" },
      resource: {
        id: "r6",
        name: "api-dev-pr-789",
        kind: "kubernetes-deployment",
        identifier: "k8s://dev/api-dev-pr-789",
      },
      version: {
        currentId: "v3",
        desiredId: "v2",
      },
      jobs: [
        {
          id: "j6",
          status: "inProgress",
          createdAt: "8 minutes ago",
          startedAt: "7 minutes ago",
        },
      ],
    },
  ],
  stats: {
    totalReleases: 48,
    totalResources: 12,
    deploymentsLast24h: 48,
    successRate: 96.5,
  },
};
