version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ctrlplane
      POSTGRES_PASSWORD: ctrlplane
      POSTGRES_DB: ctrlplane
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webservice:
    image: ctrlplane/webservice
    container_name: webservice
    environment:
      BASE_URL: "http://127.0.0.1" # <set your instance url>
      AUTH_SECRET: "<auth-secret>"
      DATABASE_URL: postgres://ctrlplane:ctrlplane@postgres:5432/ctrlplane
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"

  job-policy-checker:
    image: ctrlplane/my-job-policy-checker-image
    container_name: job-policy-checker
    environment:
      POSTGRES_URL: postgres://ctrlplane:ctrlplane@postgres:5432/ctrlplane
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
