global:
  extraEnvFrom: {}
  extraEnv: {}

  common:
    labels: {}
    annotations: {}

  redis:
    host: ""
    port: 6379
    password: ""

  postgresql:
    user: "ctrlplane"
    password: "ctrlplane"
    host: ""
    port: 6379
    database: "ctrlplane"

webservice:
  install: true

job-policy-checker:
  install: true

migrations:
  install: true

ingress:
  create: true
  class: ""
  labels: {}
  annotations: {}
