name: "JSON Key Extractor"
description: "A composite action that parses a JSON string and extracts the value of a specified key."
inputs:
  json-output:
    description: "The JSON string from which to extract a value."
    required: true
  key:
    description: "The key for which the value should be extracted from the JSON object."
    required: true
outputs:
  value:
    description: "The extracted value associated with the specified key."
runs:
  using: "composite"
  steps:
    - name: Extract value from JSON
      id: extract
      shell: bash
      run: |
        value=$(echo "${{ inputs.json-output }}" | jq -r ".${{ inputs.key }}")
        echo "value=${value}" >> $GITHUB_OUTPUT
