/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class UpdateTarget200Response {
  "id": string;
  "name": string;
  "workspaceId": string;
  "kind": string;
  "identifier": string;
  "version": string;
  "config": { [key: string]: any };
  "metadata": { [key: string]: string };

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "workspaceId",
      baseName: "workspaceId",
      type: "string",
    },
    {
      name: "kind",
      baseName: "kind",
      type: "string",
    },
    {
      name: "identifier",
      baseName: "identifier",
      type: "string",
    },
    {
      name: "version",
      baseName: "version",
      type: "string",
    },
    {
      name: "config",
      baseName: "config",
      type: "{ [key: string]: any; }",
    },
    {
      name: "metadata",
      baseName: "metadata",
      type: "{ [key: string]: string; }",
    },
  ];

  static getAttributeTypeMap() {
    return UpdateTarget200Response.attributeTypeMap;
  }
}
