/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { UpsertTargetsRequestTargetsInner } from "./upsertTargetsRequestTargetsInner";

export class UpsertTargetsRequest {
  "workspaceId": string;
  "targets": Array<UpsertTargetsRequestTargetsInner>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "workspaceId",
      baseName: "workspaceId",
      type: "string",
    },
    {
      name: "targets",
      baseName: "targets",
      type: "Array<UpsertTargetsRequestTargetsInner>",
    },
  ];

  static getAttributeTypeMap() {
    return UpsertTargetsRequest.attributeTypeMap;
  }
}
