package relationshipeval

import (
	"context"
	"fmt"
	"regexp"

	"workspace-engine/pkg/db"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

type PostgresGetter struct{}

func (g *PostgresGetter) GetEntityInfo(ctx context.Context, entityType string, entityID uuid.UUID) (*EntityInfo, error) {
	pool := db.GetPool(ctx)

	switch entityType {
	case "resource":
		var info EntityInfo
		err := pool.QueryRow(ctx, getResourceSQL, entityID).Scan(
			&info.ID, &info.WorkspaceID,
			new(string), new(string), new(string), new(string),
			new(*string), new(map[string]any), new(map[string]string),
			new(pgtype.Timestamptz), new(pgtype.Timestamptz),
		)
		if err != nil {
			return nil, fmt.Errorf("get resource %s: %w", entityID, err)
		}
		info.EntityType = "resource"
		info.Raw = buildResourceMap(ctx, entityID, pool)
		return &info, nil

	case "deployment":
		var info EntityInfo
		err := pool.QueryRow(ctx, getDeploymentSQL, entityID).Scan(
			&info.ID, &info.WorkspaceID,
			new(string), new(string), new(*string),
			new(*string), new(map[string]any),
		)
		if err != nil {
			return nil, fmt.Errorf("get deployment %s: %w", entityID, err)
		}
		info.EntityType = "deployment"
		info.Raw = buildDeploymentMap(ctx, entityID, pool)
		return &info, nil

	case "environment":
		var info EntityInfo
		err := pool.QueryRow(ctx, getEnvironmentSQL, entityID).Scan(
			&info.ID, &info.WorkspaceID,
			new(string), new(*string),
			new(pgtype.Timestamptz),
		)
		if err != nil {
			return nil, fmt.Errorf("get environment %s: %w", entityID, err)
		}
		info.EntityType = "environment"
		info.Raw = buildEnvironmentMap(ctx, entityID, pool)
		return &info, nil

	default:
		return nil, fmt.Errorf("unknown entity type %q for id %s", entityType, entityID)
	}
}

func (g *PostgresGetter) GetRulesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]RuleInfo, error) {
	pool := db.GetPool(ctx)
	q := db.New(pool)

	rows, err := q.GetRelationshipRulesForWorkspace(ctx, workspaceID)
	if err != nil {
		return nil, fmt.Errorf("get rules for workspace %s: %w", workspaceID, err)
	}

	rules := make([]RuleInfo, 0, len(rows))
	for _, row := range rows {
		fromType, toType, err := parseTypesFromCel(row.Cel)
		if err != nil {
			return nil, fmt.Errorf("parse types from CEL for rule %s: %w", row.ID, err)
		}
		rules = append(rules, RuleInfo{
			ID:        row.ID,
			Reference: row.Reference,
			Cel:       row.Cel,
			FromType:  fromType,
			ToType:    toType,
		})
	}
	return rules, nil
}

var celTypePattern = regexp.MustCompile(`^from\.type\s*==\s*"([^"]+)"\s*&&\s*to\.type\s*==\s*"([^"]+)"`)

// parseTypesFromCel extracts the from/to entity types from a compiled CEL
// expression. The expression is expected to start with the type guards
// generated by ruleToCelExpression: from.type == "X" && to.type == "Y".
func parseTypesFromCel(cel string) (fromType, toType string, err error) {
	m := celTypePattern.FindStringSubmatch(cel)
	if m == nil {
		return "", "", fmt.Errorf("CEL expression does not start with expected type guards: %q", cel)
	}
	return m[1], m[2], nil
}

func (g *PostgresGetter) StreamCandidateEntities(ctx context.Context, workspaceID uuid.UUID, entityType string, batchSize int, batches chan<- []EntityInfo) error {
	defer close(batches)

	var query string
	var buildMap func(row []any) map[string]any
	switch entityType {
	case "resource":
		query = listResourcesSQL
		buildMap = rowToResourceMap
	case "deployment":
		query = listDeploymentsSQL
		buildMap = rowToDeploymentMap
	case "environment":
		query = listEnvironmentsSQL
		buildMap = rowToEnvironmentMap
	default:
		return fmt.Errorf("unknown entity type: %s", entityType)
	}

	rows, err := db.GetPool(ctx).Query(ctx, query, workspaceID)
	if err != nil {
		return fmt.Errorf("query %s entities for workspace %s: %w", entityType, workspaceID, err)
	}
	defer rows.Close()

	batch := make([]EntityInfo, 0, batchSize)
	for rows.Next() {
		values, err := rows.Values()
		if err != nil {
			return fmt.Errorf("scan %s row: %w", entityType, err)
		}

		id, ok := values[0].([16]byte)
		if !ok {
			continue
		}
		entityID := uuid.UUID(id)

		wsID, ok := values[1].([16]byte)
		if !ok {
			continue
		}

		batch = append(batch, EntityInfo{
			ID:          entityID,
			WorkspaceID: uuid.UUID(wsID),
			EntityType:  entityType,
			Raw:         buildMap(values),
		})

		if len(batch) >= batchSize {
			select {
			case batches <- batch:
			case <-ctx.Done():
				return ctx.Err()
			}
			batch = make([]EntityInfo, 0, batchSize)
		}
	}

	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate %s entities: %w", entityType, err)
	}

	if len(batch) > 0 {
		select {
		case batches <- batch:
		case <-ctx.Done():
			return ctx.Err()
		}
	}

	return nil
}

func (g *PostgresGetter) GetExistingRelationships(ctx context.Context, entityID uuid.UUID) ([]ExistingRelationship, error) {
	// TODO: implement query against computed_entity_relationship table once schema is defined
	return nil, nil
}

// --- SQL ---

const getResourceSQL = `
SELECT id, workspace_id, name, kind, version, identifier,
       provider_id, config, metadata, created_at, updated_at
FROM resource
WHERE id = $1 AND deleted_at IS NULL
`

const getDeploymentSQL = `
SELECT id, workspace_id, name, slug, description, job_agent_id, job_agent_config
FROM deployment
WHERE id = $1
`

const getEnvironmentSQL = `
SELECT id, workspace_id, name, description, created_at
FROM environment
WHERE id = $1
`

const listResourcesSQL = `
SELECT id, workspace_id, name, kind, version, identifier,
       provider_id, config, metadata, created_at, updated_at
FROM resource
WHERE workspace_id = $1 AND deleted_at IS NULL
`

const listDeploymentsSQL = `
SELECT id, workspace_id, name, slug, description, job_agent_id, job_agent_config, metadata
FROM deployment
WHERE workspace_id = $1
`

const listEnvironmentsSQL = `
SELECT id, workspace_id, name, description, metadata, created_at
FROM environment
WHERE workspace_id = $1
`

// --- Map builders (single-row lookups via pool.QueryRow) ---

func buildResourceMap(ctx context.Context, id uuid.UUID, pool *pgxpool.Pool) map[string]any {
	var (
		name, kind, version, identifier string
		providerID                      *string
		config                          map[string]any
		metadata                        map[string]string
		createdAt, updatedAt            pgtype.Timestamptz
	)
	_ = pool.QueryRow(ctx, getResourceSQL, id).Scan(
		new(uuid.UUID), new(uuid.UUID),
		&name, &kind, &version, &identifier,
		&providerID, &config, &metadata, &createdAt, &updatedAt,
	)
	m := map[string]any{
		"type":       "resource",
		"id":         id.String(),
		"name":       name,
		"kind":       kind,
		"version":    version,
		"identifier": identifier,
		"config":     config,
		"metadata":   stringMapToAnyMap(metadata),
	}
	if providerID != nil {
		m["providerId"] = *providerID
	}
	return m
}

func buildDeploymentMap(ctx context.Context, id uuid.UUID, pool *pgxpool.Pool) map[string]any {
	var (
		name, slug   string
		description  *string
		jobAgentID   *string
		jobAgentConf map[string]any
	)
	_ = pool.QueryRow(ctx, getDeploymentSQL, id).Scan(
		new(uuid.UUID), new(uuid.UUID),
		&name, &slug, &description, &jobAgentID, &jobAgentConf,
	)
	m := map[string]any{
		"type":           "deployment",
		"id":             id.String(),
		"name":           name,
		"slug":           slug,
		"jobAgentConfig": jobAgentConf,
	}
	if description != nil {
		m["description"] = *description
	}
	if jobAgentID != nil {
		m["jobAgentId"] = *jobAgentID
	}
	return m
}

func buildEnvironmentMap(ctx context.Context, id uuid.UUID, pool *pgxpool.Pool) map[string]any {
	var (
		name        string
		description *string
		createdAt   pgtype.Timestamptz
	)
	_ = pool.QueryRow(ctx, getEnvironmentSQL, id).Scan(
		new(uuid.UUID), new(uuid.UUID),
		&name, &description, &createdAt,
	)
	m := map[string]any{
		"type": "environment",
		"id":   id.String(),
		"name": name,
	}
	if description != nil {
		m["description"] = *description
	}
	return m
}

// --- Map builders (from row values in streaming) ---

func rowToResourceMap(values []any) map[string]any {
	m := map[string]any{
		"type": "resource",
	}
	if len(values) > 0 {
		if id, ok := values[0].([16]byte); ok {
			m["id"] = uuid.UUID(id).String()
		}
	}
	if len(values) > 2 {
		m["name"] = values[2]
	}
	if len(values) > 3 {
		m["kind"] = values[3]
	}
	if len(values) > 4 {
		m["version"] = values[4]
	}
	if len(values) > 5 {
		m["identifier"] = values[5]
	}
	if len(values) > 7 {
		m["config"] = values[7]
	}
	if len(values) > 8 {
		if md, ok := values[8].(map[string]string); ok {
			m["metadata"] = stringMapToAnyMap(md)
		}
	}
	return m
}

func rowToDeploymentMap(values []any) map[string]any {
	m := map[string]any{
		"type": "deployment",
	}
	if len(values) > 0 {
		if id, ok := values[0].([16]byte); ok {
			m["id"] = uuid.UUID(id).String()
		}
	}
	if len(values) > 2 {
		m["name"] = values[2]
	}
	if len(values) > 3 {
		m["slug"] = values[3]
	}
	if len(values) > 4 {
		m["description"] = values[4]
	}
	if len(values) > 7 {
		if md, ok := values[7].(map[string]string); ok {
			m["metadata"] = stringMapToAnyMap(md)
		}
	}
	return m
}

func rowToEnvironmentMap(values []any) map[string]any {
	m := map[string]any{
		"type": "environment",
	}
	if len(values) > 0 {
		if id, ok := values[0].([16]byte); ok {
			m["id"] = uuid.UUID(id).String()
		}
	}
	if len(values) > 2 {
		m["name"] = values[2]
	}
	if len(values) > 3 {
		m["description"] = values[3]
	}
	if len(values) > 4 {
		if md, ok := values[4].(map[string]string); ok {
			m["metadata"] = stringMapToAnyMap(md)
		}
	}
	return m
}

func stringMapToAnyMap(m map[string]string) map[string]any {
	if m == nil {
		return nil
	}
	result := make(map[string]any, len(m))
	for k, v := range m {
		result[k] = v
	}
	return result
}
