/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateTargetsRequestTargetsInner } from "./CreateTargetsRequestTargetsInner";
import { mapValues } from "../runtime";
import {
  CreateTargetsRequestTargetsInnerFromJSON,
  CreateTargetsRequestTargetsInnerFromJSONTyped,
  CreateTargetsRequestTargetsInnerToJSON,
  CreateTargetsRequestTargetsInnerToJSONTyped,
} from "./CreateTargetsRequestTargetsInner";

/**
 *
 * @export
 * @interface CreateTargetsRequest
 */
export interface CreateTargetsRequest {
  /**
   *
   * @type {string}
   * @memberof CreateTargetsRequest
   */
  workspaceId: string;
  /**
   *
   * @type {Array<CreateTargetsRequestTargetsInner>}
   * @memberof CreateTargetsRequest
   */
  targets: Array<CreateTargetsRequestTargetsInner>;
}

/**
 * Check if a given object implements the CreateTargetsRequest interface.
 */
export function instanceOfCreateTargetsRequest(
  value: object,
): value is CreateTargetsRequest {
  if (!("workspaceId" in value) || value["workspaceId"] === undefined)
    return false;
  if (!("targets" in value) || value["targets"] === undefined) return false;
  return true;
}

export function CreateTargetsRequestFromJSON(json: any): CreateTargetsRequest {
  return CreateTargetsRequestFromJSONTyped(json, false);
}

export function CreateTargetsRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTargetsRequest {
  if (json == null) {
    return json;
  }
  return {
    workspaceId: json["workspaceId"],
    targets: (json["targets"] as Array<any>).map(
      CreateTargetsRequestTargetsInnerFromJSON,
    ),
  };
}

export function CreateTargetsRequestToJSON(json: any): CreateTargetsRequest {
  return CreateTargetsRequestToJSONTyped(json, false);
}

export function CreateTargetsRequestToJSONTyped(
  value?: CreateTargetsRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    workspaceId: value["workspaceId"],
    targets: (value["targets"] as Array<any>).map(
      CreateTargetsRequestTargetsInnerToJSON,
    ),
  };
}
