/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateTargets400Response
 */
export interface CreateTargets400Response {
  /**
   *
   * @type {string}
   * @memberof CreateTargets400Response
   */
  error?: string;
}

/**
 * Check if a given object implements the CreateTargets400Response interface.
 */
export function instanceOfCreateTargets400Response(
  value: object,
): value is CreateTargets400Response {
  return true;
}

export function CreateTargets400ResponseFromJSON(
  json: any,
): CreateTargets400Response {
  return CreateTargets400ResponseFromJSONTyped(json, false);
}

export function CreateTargets400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTargets400Response {
  if (json == null) {
    return json;
  }
  return {
    error: json["error"] == null ? undefined : json["error"],
  };
}

export function CreateTargets400ResponseToJSON(
  json: any,
): CreateTargets400Response {
  return CreateTargets400ResponseToJSONTyped(json, false);
}

export function CreateTargets400ResponseToJSONTyped(
  value?: CreateTargets400Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value["error"],
  };
}
