/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateTargetInput
 */
export interface CreateTargetInput {
  /**
   *
   * @type {string}
   * @memberof CreateTargetInput
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateTargetInput
   */
  version: string;
  /**
   *
   * @type {string}
   * @memberof CreateTargetInput
   */
  kind: string;
  /**
   *
   * @type {string}
   * @memberof CreateTargetInput
   */
  identifier: string;
  /**
   *
   * @type {string}
   * @memberof CreateTargetInput
   */
  workspaceId: string;
  /**
   *
   * @type {object}
   * @memberof CreateTargetInput
   */
  config: object;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof CreateTargetInput
   */
  metadata: { [key: string]: string };
}

/**
 * Check if a given object implements the CreateTargetInput interface.
 */
export function instanceOfCreateTargetInput(
  value: object,
): value is CreateTargetInput {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("version" in value) || value["version"] === undefined) return false;
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("identifier" in value) || value["identifier"] === undefined)
    return false;
  if (!("workspaceId" in value) || value["workspaceId"] === undefined)
    return false;
  if (!("config" in value) || value["config"] === undefined) return false;
  if (!("metadata" in value) || value["metadata"] === undefined) return false;
  return true;
}

export function CreateTargetInputFromJSON(json: any): CreateTargetInput {
  return CreateTargetInputFromJSONTyped(json, false);
}

export function CreateTargetInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTargetInput {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    version: json["version"],
    kind: json["kind"],
    identifier: json["identifier"],
    workspaceId: json["workspaceId"],
    config: json["config"],
    metadata: json["metadata"],
  };
}

export function CreateTargetInputToJSON(value?: CreateTargetInput | null): any {
  if (value == null) {
    return value;
  }
  return {
    name: value["name"],
    version: value["version"],
    kind: value["kind"],
    identifier: value["identifier"],
    workspaceId: value["workspaceId"],
    config: value["config"],
    metadata: value["metadata"],
  };
}
