/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface GetJob200ResponseDeployment
 */
export interface GetJob200ResponseDeployment {
  /**
   *
   * @type {string}
   * @memberof GetJob200ResponseDeployment
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetJob200ResponseDeployment
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof GetJob200ResponseDeployment
   */
  slug: string;
}

/**
 * Check if a given object implements the GetJob200ResponseDeployment interface.
 */
export function instanceOfGetJob200ResponseDeployment(
  value: object,
): value is GetJob200ResponseDeployment {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("slug" in value) || value["slug"] === undefined) return false;
  return true;
}

export function GetJob200ResponseDeploymentFromJSON(
  json: any,
): GetJob200ResponseDeployment {
  return GetJob200ResponseDeploymentFromJSONTyped(json, false);
}

export function GetJob200ResponseDeploymentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetJob200ResponseDeployment {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"] == null ? undefined : json["name"],
    slug: json["slug"],
  };
}

export function GetJob200ResponseDeploymentToJSON(
  value?: GetJob200ResponseDeployment | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    name: value["name"],
    slug: value["slug"],
  };
}
