/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetNextJobs200ResponseJobExecutionsInner } from './GetNextJobs200ResponseJobExecutionsInner';
import {
    GetNextJobs200ResponseJobExecutionsInnerFromJSON,
    GetNextJobs200ResponseJobExecutionsInnerFromJSONTyped,
    GetNextJobs200ResponseJobExecutionsInnerToJSON,
} from './GetNextJobs200ResponseJobExecutionsInner';

/**
 * 
 * @export
 * @interface GetNextJobs200Response
 */
export interface GetNextJobs200Response {
    /**
     * 
     * @type {Array<GetNextJobs200ResponseJobExecutionsInner>}
     * @memberof GetNextJobs200Response
     */
    jobExecutions?: Array<GetNextJobs200ResponseJobExecutionsInner>;
}

/**
 * Check if a given object implements the GetNextJobs200Response interface.
 */
export function instanceOfGetNextJobs200Response(value: object): value is GetNextJobs200Response {
    return true;
}

export function GetNextJobs200ResponseFromJSON(json: any): GetNextJobs200Response {
    return GetNextJobs200ResponseFromJSONTyped(json, false);
}

export function GetNextJobs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNextJobs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jobExecutions': json['jobExecutions'] == null ? undefined : ((json['jobExecutions'] as Array<any>).map(GetNextJobs200ResponseJobExecutionsInnerFromJSON)),
    };
}

export function GetNextJobs200ResponseToJSON(value?: GetNextJobs200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobExecutions': value['jobExecutions'] == null ? undefined : ((value['jobExecutions'] as Array<any>).map(GetNextJobs200ResponseJobExecutionsInnerToJSON)),
    };
}

