/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface GetTargetVariable200Response
 */
export interface GetTargetVariable200Response {
  /**
   *
   * @type {string}
   * @memberof GetTargetVariable200Response
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetTargetVariable200Response
   */
  targetId: string;
  /**
   *
   * @type {string}
   * @memberof GetTargetVariable200Response
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof GetTargetVariable200Response
   */
  value?: string;
  /**
   *
   * @type {boolean}
   * @memberof GetTargetVariable200Response
   */
  sensitive: boolean;
}

/**
 * Check if a given object implements the GetTargetVariable200Response interface.
 */
export function instanceOfGetTargetVariable200Response(
  value: object,
): value is GetTargetVariable200Response {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("targetId" in value) || value["targetId"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("sensitive" in value) || value["sensitive"] === undefined) return false;
  return true;
}

export function GetTargetVariable200ResponseFromJSON(
  json: any,
): GetTargetVariable200Response {
  return GetTargetVariable200ResponseFromJSONTyped(json, false);
}

export function GetTargetVariable200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTargetVariable200Response {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    targetId: json["targetId"],
    name: json["name"],
    value: json["value"] == null ? undefined : json["value"],
    sensitive: json["sensitive"],
  };
}

export function GetTargetVariable200ResponseToJSON(
  value?: GetTargetVariable200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    targetId: value["targetId"],
    name: value["name"],
    value: value["value"],
    sensitive: value["sensitive"],
  };
}
