/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateJobAgentRequest
 */
export interface UpdateJobAgentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateJobAgentRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateJobAgentRequest
     */
    type: string;
}

/**
 * Check if a given object implements the UpdateJobAgentRequest interface.
 */
export function instanceOfUpdateJobAgentRequest(value: object): value is UpdateJobAgentRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function UpdateJobAgentRequestFromJSON(json: any): UpdateJobAgentRequest {
    return UpdateJobAgentRequestFromJSONTyped(json, false);
}

export function UpdateJobAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateJobAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
    };
}

export function UpdateJobAgentRequestToJSON(value?: UpdateJobAgentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
    };
}

