/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UpdateTargetRequestVariablesInner } from "./UpdateTargetRequestVariablesInner";
import { mapValues } from "../runtime";
import {
  UpdateTargetRequestVariablesInnerFromJSON,
  UpdateTargetRequestVariablesInnerFromJSONTyped,
  UpdateTargetRequestVariablesInnerToJSON,
} from "./UpdateTargetRequestVariablesInner";

/**
 *
 * @export
 * @interface UpdateTargetRequest
 */
export interface UpdateTargetRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateTargetRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateTargetRequest
   */
  version?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateTargetRequest
   */
  kind?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateTargetRequest
   */
  identifier?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateTargetRequest
   */
  workspaceId?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof UpdateTargetRequest
   */
  metadata?: { [key: string]: string };
  /**
   *
   * @type {Array<UpdateTargetRequestVariablesInner>}
   * @memberof UpdateTargetRequest
   */
  variables?: Array<UpdateTargetRequestVariablesInner>;
}

/**
 * Check if a given object implements the UpdateTargetRequest interface.
 */
export function instanceOfUpdateTargetRequest(
  value: object,
): value is UpdateTargetRequest {
  return true;
}

export function UpdateTargetRequestFromJSON(json: any): UpdateTargetRequest {
  return UpdateTargetRequestFromJSONTyped(json, false);
}

export function UpdateTargetRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTargetRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"] == null ? undefined : json["name"],
    version: json["version"] == null ? undefined : json["version"],
    kind: json["kind"] == null ? undefined : json["kind"],
    identifier: json["identifier"] == null ? undefined : json["identifier"],
    workspaceId: json["workspaceId"] == null ? undefined : json["workspaceId"],
    metadata: json["metadata"] == null ? undefined : json["metadata"],
    variables:
      json["variables"] == null
        ? undefined
        : (json["variables"] as Array<any>).map(
            UpdateTargetRequestVariablesInnerFromJSON,
          ),
  };
}

export function UpdateTargetRequestToJSON(
  value?: UpdateTargetRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    name: value["name"],
    version: value["version"],
    kind: value["kind"],
    identifier: value["identifier"],
    workspaceId: value["workspaceId"],
    metadata: value["metadata"],
    variables:
      value["variables"] == null
        ? undefined
        : (value["variables"] as Array<any>).map(
            UpdateTargetRequestVariablesInnerToJSON,
          ),
  };
}
