/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UpdateTargetRequestTarget } from "./UpdateTargetRequestTarget";
import { mapValues } from "../runtime";
import {
  UpdateTargetRequestTargetFromJSON,
  UpdateTargetRequestTargetFromJSONTyped,
  UpdateTargetRequestTargetToJSON,
} from "./UpdateTargetRequestTarget";

/**
 *
 * @export
 * @interface UpdateTargetRequest
 */
export interface UpdateTargetRequest {
  /**
   *
   * @type {UpdateTargetRequestTarget}
   * @memberof UpdateTargetRequest
   */
  target?: UpdateTargetRequestTarget;
}

/**
 * Check if a given object implements the UpdateTargetRequest interface.
 */
export function instanceOfUpdateTargetRequest(
  value: object,
): value is UpdateTargetRequest {
  return true;
}

export function UpdateTargetRequestFromJSON(json: any): UpdateTargetRequest {
  return UpdateTargetRequestFromJSONTyped(json, false);
}

export function UpdateTargetRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTargetRequest {
  if (json == null) {
    return json;
  }
  return {
    target:
      json["target"] == null
        ? undefined
        : UpdateTargetRequestTargetFromJSON(json["target"]),
  };
}

export function UpdateTargetRequestToJSON(
  value?: UpdateTargetRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    target: UpdateTargetRequestTargetToJSON(value["target"]),
  };
}
