/* tslint:disable */
/* eslint-disable */
/**
 * Ctrlplane API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface UpsertTargetsRequestTargetsInnerVariablesInnerValue
 */
export interface UpsertTargetsRequestTargetsInnerVariablesInnerValue {}

/**
 * Check if a given object implements the UpsertTargetsRequestTargetsInnerVariablesInnerValue interface.
 */
export function instanceOfUpsertTargetsRequestTargetsInnerVariablesInnerValue(
  value: object,
): value is UpsertTargetsRequestTargetsInnerVariablesInnerValue {
  return true;
}

export function UpsertTargetsRequestTargetsInnerVariablesInnerValueFromJSON(
  json: any,
): UpsertTargetsRequestTargetsInnerVariablesInnerValue {
  return UpsertTargetsRequestTargetsInnerVariablesInnerValueFromJSONTyped(
    json,
    false,
  );
}

export function UpsertTargetsRequestTargetsInnerVariablesInnerValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpsertTargetsRequestTargetsInnerVariablesInnerValue {
  return json;
}

export function UpsertTargetsRequestTargetsInnerVariablesInnerValueToJSON(
  json: any,
): UpsertTargetsRequestTargetsInnerVariablesInnerValue {
  return UpsertTargetsRequestTargetsInnerVariablesInnerValueToJSONTyped(
    json,
    false,
  );
}

export function UpsertTargetsRequestTargetsInnerVariablesInnerValueToJSONTyped(
  value?: UpsertTargetsRequestTargetsInnerVariablesInnerValue | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
