// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi

import (
	"encoding/json"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ApprovalStatus.
const (
	ApprovalStatusApproved ApprovalStatus = "approved"
	ApprovalStatusRejected ApprovalStatus = "rejected"
)

// Defines values for DeploymentVersionStatus.
const (
	DeploymentVersionStatusBuilding    DeploymentVersionStatus = "building"
	DeploymentVersionStatusFailed      DeploymentVersionStatus = "failed"
	DeploymentVersionStatusReady       DeploymentVersionStatus = "ready"
	DeploymentVersionStatusRejected    DeploymentVersionStatus = "rejected"
	DeploymentVersionStatusUnspecified DeploymentVersionStatus = "unspecified"
)

// Defines values for JobStatus.
const (
	ActionRequired      JobStatus = "actionRequired"
	Cancelled           JobStatus = "cancelled"
	ExternalRunNotFound JobStatus = "externalRunNotFound"
	Failure             JobStatus = "failure"
	InProgress          JobStatus = "inProgress"
	InvalidIntegration  JobStatus = "invalidIntegration"
	InvalidJobAgent     JobStatus = "invalidJobAgent"
	Pending             JobStatus = "pending"
	Skipped             JobStatus = "skipped"
	Successful          JobStatus = "successful"
)

// Defines values for NullValue.
const (
	True NullValue = true
)

// Defines values for PropertyMatcherOperator.
const (
	Contains   PropertyMatcherOperator = "contains"
	EndsWith   PropertyMatcherOperator = "endsWith"
	Equals     PropertyMatcherOperator = "equals"
	NotEquals  PropertyMatcherOperator = "notEquals"
	Regex      PropertyMatcherOperator = "regex"
	StartsWith PropertyMatcherOperator = "startsWith"
)

// AnyApprovalRule defines model for AnyApprovalRule.
type AnyApprovalRule struct {
	MinApprovals int32 `json:"minApprovals"`
}

// ApprovalStatus defines model for ApprovalStatus.
type ApprovalStatus string

// BooleanValue defines model for BooleanValue.
type BooleanValue = bool

// ComputeReleaseTargetsRequest defines model for ComputeReleaseTargetsRequest.
type ComputeReleaseTargetsRequest struct {
	Deployments  []Deployment  `json:"deployments"`
	Environments []Environment `json:"environments"`
	Resources    []Resource    `json:"resources"`
}

// ComputeReleaseTargetsResponse defines model for ComputeReleaseTargetsResponse.
type ComputeReleaseTargetsResponse struct {
	ReleaseTargets []ReleaseTarget `json:"releaseTargets"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	Description      *string                `json:"description,omitempty"`
	Id               string                 `json:"id"`
	JobAgentConfig   map[string]interface{} `json:"jobAgentConfig"`
	JobAgentId       *string                `json:"jobAgentId,omitempty"`
	Name             string                 `json:"name"`
	ResourceSelector *Selector              `json:"resourceSelector,omitempty"`
	Slug             string                 `json:"slug"`
	SystemId         string                 `json:"systemId"`
}

// DeploymentVariable defines model for DeploymentVariable.
type DeploymentVariable struct {
	DefaultValue *LiteralValue `json:"defaultValue,omitempty"`
	DeploymentId string        `json:"deploymentId"`
	Description  *string       `json:"description,omitempty"`
	Id           string        `json:"id"`
	Key          string        `json:"key"`
	VariableId   string        `json:"variableId"`
}

// DeploymentVariableValue defines model for DeploymentVariableValue.
type DeploymentVariableValue struct {
	DeploymentVariableId string    `json:"deploymentVariableId"`
	Id                   string    `json:"id"`
	Priority             int64     `json:"priority"`
	ResourceSelector     *Selector `json:"resourceSelector,omitempty"`
	Value                Value     `json:"value"`
}

// DeploymentVersion defines model for DeploymentVersion.
type DeploymentVersion struct {
	Config         map[string]interface{}  `json:"config"`
	CreatedAt      string                  `json:"createdAt"`
	DeploymentId   string                  `json:"deploymentId"`
	Id             string                  `json:"id"`
	JobAgentConfig map[string]interface{}  `json:"jobAgentConfig"`
	Message        *string                 `json:"message,omitempty"`
	Name           string                  `json:"name"`
	Status         DeploymentVersionStatus `json:"status"`
	Tag            string                  `json:"tag"`
}

// DeploymentVersionStatus defines model for DeploymentVersionStatus.
type DeploymentVersionStatus string

// Environment defines model for Environment.
type Environment struct {
	CreatedAt        string    `json:"createdAt"`
	Description      *string   `json:"description,omitempty"`
	Id               string    `json:"id"`
	Name             string    `json:"name"`
	ResourceSelector *Selector `json:"resourceSelector,omitempty"`
	SystemId         string    `json:"systemId"`
}

// IntegerValue defines model for IntegerValue.
type IntegerValue = int

// Job defines model for Job.
type Job struct {
	CompletedAt    *time.Time             `json:"completedAt,omitempty"`
	CreatedAt      time.Time              `json:"createdAt"`
	DeploymentId   string                 `json:"deploymentId"`
	EnvironmentId  string                 `json:"environmentId"`
	ExternalId     *string                `json:"externalId,omitempty"`
	Id             string                 `json:"id"`
	JobAgentConfig map[string]interface{} `json:"jobAgentConfig"`
	JobAgentId     string                 `json:"jobAgentId"`
	ReleaseId      string                 `json:"releaseId"`
	ResourceId     string                 `json:"resourceId"`
	StartedAt      *time.Time             `json:"startedAt,omitempty"`
	Status         JobStatus              `json:"status"`
	UpdatedAt      time.Time              `json:"updatedAt"`
}

// JobAgent defines model for JobAgent.
type JobAgent struct {
	Config      map[string]interface{} `json:"config"`
	Id          string                 `json:"id"`
	Name        string                 `json:"name"`
	Type        string                 `json:"type"`
	WorkspaceId string                 `json:"workspaceId"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// JsonSelector defines model for JsonSelector.
type JsonSelector struct {
	Json map[string]interface{} `json:"json"`
}

// ListDeploymentsRequest defines model for ListDeploymentsRequest.
type ListDeploymentsRequest struct {
	DeploymentSelector *Selector `json:"deploymentSelector,omitempty"`
	WorkspaceId        string    `json:"workspaceId"`
}

// ListDeploymentsResponse defines model for ListDeploymentsResponse.
type ListDeploymentsResponse struct {
	Deployments []Deployment `json:"deployments"`
}

// ListReleaseTargetsRequest defines model for ListReleaseTargetsRequest.
type ListReleaseTargetsRequest struct {
	DeploymentSelector  *Selector `json:"deploymentSelector,omitempty"`
	EnvironmentSelector *Selector `json:"environmentSelector,omitempty"`
	ResourceSelector    *Selector `json:"resourceSelector,omitempty"`
	WorkspaceId         string    `json:"workspaceId"`
}

// ListReleaseTargetsResponse defines model for ListReleaseTargetsResponse.
type ListReleaseTargetsResponse struct {
	ReleaseTargets []ReleaseTarget `json:"releaseTargets"`
}

// LiteralValue defines model for LiteralValue.
type LiteralValue struct {
	union json.RawMessage
}

// NullValue defines model for NullValue.
type NullValue bool

// NumberValue defines model for NumberValue.
type NumberValue = float32

// ObjectValue defines model for ObjectValue.
type ObjectValue struct {
	Object map[string]interface{} `json:"object"`
}

// Policy defines model for Policy.
type Policy struct {
	CreatedAt   string                 `json:"createdAt"`
	Description *string                `json:"description,omitempty"`
	Id          string                 `json:"id"`
	Name        string                 `json:"name"`
	Rules       []PolicyRule           `json:"rules"`
	Selectors   []PolicyTargetSelector `json:"selectors"`
	WorkspaceId string                 `json:"workspaceId"`
}

// PolicyRule defines model for PolicyRule.
type PolicyRule struct {
	AnyApproval *AnyApprovalRule `json:"anyApproval,omitempty"`
	CreatedAt   string           `json:"createdAt"`
	Id          string           `json:"id"`
	PolicyId    string           `json:"policyId"`
}

// PolicyTargetSelector defines model for PolicyTargetSelector.
type PolicyTargetSelector struct {
	DeploymentSelector  *Selector `json:"deploymentSelector,omitempty"`
	EnvironmentSelector *Selector `json:"environmentSelector,omitempty"`
	Id                  string    `json:"id"`
	ResourceSelector    *Selector `json:"resourceSelector,omitempty"`
}

// PropertyMatcher defines model for PropertyMatcher.
type PropertyMatcher struct {
	FromProperty []string                `json:"fromProperty"`
	Operator     PropertyMatcherOperator `json:"operator"`
	ToProperty   []string                `json:"toProperty"`
}

// PropertyMatcherOperator defines model for PropertyMatcher.Operator.
type PropertyMatcherOperator string

// ReferenceValue defines model for ReferenceValue.
type ReferenceValue struct {
	Path      []string `json:"path"`
	Reference string   `json:"reference"`
}

// RelationshipRule defines model for RelationshipRule.
type RelationshipRule struct {
	Description      *string           `json:"description,omitempty"`
	FromSelector     *Selector         `json:"fromSelector,omitempty"`
	FromType         string            `json:"fromType"`
	Id               string            `json:"id"`
	Metadata         map[string]string `json:"metadata"`
	Name             string            `json:"name"`
	PropertyMatchers []PropertyMatcher `json:"propertyMatchers"`
	Reference        string            `json:"reference"`
	RelationshipType string            `json:"relationshipType"`
	ToSelector       *Selector         `json:"toSelector,omitempty"`
	ToType           string            `json:"toType"`
}

// Release defines model for Release.
type Release struct {
	CreatedAt          string                  `json:"createdAt"`
	EncryptedVariables []string                `json:"encryptedVariables"`
	ReleaseTarget      ReleaseTarget           `json:"releaseTarget"`
	Variables          map[string]LiteralValue `json:"variables"`
	Version            DeploymentVersion       `json:"version"`
}

// ReleaseTarget defines model for ReleaseTarget.
type ReleaseTarget struct {
	DeploymentId  string `json:"deploymentId"`
	EnvironmentId string `json:"environmentId"`
	ResourceId    string `json:"resourceId"`
}

// Resource defines model for Resource.
type Resource struct {
	Config      map[string]interface{} `json:"config"`
	CreatedAt   string                 `json:"createdAt"`
	DeletedAt   *string                `json:"deletedAt,omitempty"`
	Id          string                 `json:"id"`
	Identifier  string                 `json:"identifier"`
	Kind        string                 `json:"kind"`
	LockedAt    *string                `json:"lockedAt,omitempty"`
	Metadata    map[string]string      `json:"metadata"`
	Name        string                 `json:"name"`
	ProviderId  *string                `json:"providerId,omitempty"`
	UpdatedAt   *string                `json:"updatedAt,omitempty"`
	Version     string                 `json:"version"`
	WorkspaceId string                 `json:"workspaceId"`
}

// ResourceVariable defines model for ResourceVariable.
type ResourceVariable struct {
	Key        string `json:"key"`
	ResourceId string `json:"resourceId"`
	Value      Value  `json:"value"`
}

// Selector defines model for Selector.
type Selector struct {
	union json.RawMessage
}

// SensitiveValue defines model for SensitiveValue.
type SensitiveValue struct {
	ValueHash string `json:"valueHash"`
}

// StringValue defines model for StringValue.
type StringValue = string

// System defines model for System.
type System struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	WorkspaceId string  `json:"workspaceId"`
}

// UserApprovalRecord defines model for UserApprovalRecord.
type UserApprovalRecord struct {
	CreatedAt string         `json:"createdAt"`
	Reason    *string        `json:"reason,omitempty"`
	Status    ApprovalStatus `json:"status"`
	UserId    string         `json:"userId"`
	VersionId string         `json:"versionId"`
}

// Value defines model for Value.
type Value struct {
	union json.RawMessage
}

// AsBooleanValue returns the union data inside the LiteralValue as a BooleanValue
func (t LiteralValue) AsBooleanValue() (BooleanValue, error) {
	var body BooleanValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBooleanValue overwrites any union data inside the LiteralValue as the provided BooleanValue
func (t *LiteralValue) FromBooleanValue(v BooleanValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBooleanValue performs a merge with any union data inside the LiteralValue, using the provided BooleanValue
func (t *LiteralValue) MergeBooleanValue(v BooleanValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNumberValue returns the union data inside the LiteralValue as a NumberValue
func (t LiteralValue) AsNumberValue() (NumberValue, error) {
	var body NumberValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNumberValue overwrites any union data inside the LiteralValue as the provided NumberValue
func (t *LiteralValue) FromNumberValue(v NumberValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNumberValue performs a merge with any union data inside the LiteralValue, using the provided NumberValue
func (t *LiteralValue) MergeNumberValue(v NumberValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIntegerValue returns the union data inside the LiteralValue as a IntegerValue
func (t LiteralValue) AsIntegerValue() (IntegerValue, error) {
	var body IntegerValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIntegerValue overwrites any union data inside the LiteralValue as the provided IntegerValue
func (t *LiteralValue) FromIntegerValue(v IntegerValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIntegerValue performs a merge with any union data inside the LiteralValue, using the provided IntegerValue
func (t *LiteralValue) MergeIntegerValue(v IntegerValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStringValue returns the union data inside the LiteralValue as a StringValue
func (t LiteralValue) AsStringValue() (StringValue, error) {
	var body StringValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStringValue overwrites any union data inside the LiteralValue as the provided StringValue
func (t *LiteralValue) FromStringValue(v StringValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStringValue performs a merge with any union data inside the LiteralValue, using the provided StringValue
func (t *LiteralValue) MergeStringValue(v StringValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsObjectValue returns the union data inside the LiteralValue as a ObjectValue
func (t LiteralValue) AsObjectValue() (ObjectValue, error) {
	var body ObjectValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromObjectValue overwrites any union data inside the LiteralValue as the provided ObjectValue
func (t *LiteralValue) FromObjectValue(v ObjectValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeObjectValue performs a merge with any union data inside the LiteralValue, using the provided ObjectValue
func (t *LiteralValue) MergeObjectValue(v ObjectValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNullValue returns the union data inside the LiteralValue as a NullValue
func (t LiteralValue) AsNullValue() (NullValue, error) {
	var body NullValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNullValue overwrites any union data inside the LiteralValue as the provided NullValue
func (t *LiteralValue) FromNullValue(v NullValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNullValue performs a merge with any union data inside the LiteralValue, using the provided NullValue
func (t *LiteralValue) MergeNullValue(v NullValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LiteralValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LiteralValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJsonSelector returns the union data inside the Selector as a JsonSelector
func (t Selector) AsJsonSelector() (JsonSelector, error) {
	var body JsonSelector
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJsonSelector overwrites any union data inside the Selector as the provided JsonSelector
func (t *Selector) FromJsonSelector(v JsonSelector) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJsonSelector performs a merge with any union data inside the Selector, using the provided JsonSelector
func (t *Selector) MergeJsonSelector(v JsonSelector) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Selector) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Selector) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLiteralValue returns the union data inside the Value as a LiteralValue
func (t Value) AsLiteralValue() (LiteralValue, error) {
	var body LiteralValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLiteralValue overwrites any union data inside the Value as the provided LiteralValue
func (t *Value) FromLiteralValue(v LiteralValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLiteralValue performs a merge with any union data inside the Value, using the provided LiteralValue
func (t *Value) MergeLiteralValue(v LiteralValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReferenceValue returns the union data inside the Value as a ReferenceValue
func (t Value) AsReferenceValue() (ReferenceValue, error) {
	var body ReferenceValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReferenceValue overwrites any union data inside the Value as the provided ReferenceValue
func (t *Value) FromReferenceValue(v ReferenceValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReferenceValue performs a merge with any union data inside the Value, using the provided ReferenceValue
func (t *Value) MergeReferenceValue(v ReferenceValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSensitiveValue returns the union data inside the Value as a SensitiveValue
func (t Value) AsSensitiveValue() (SensitiveValue, error) {
	var body SensitiveValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSensitiveValue overwrites any union data inside the Value as the provided SensitiveValue
func (t *Value) FromSensitiveValue(v SensitiveValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSensitiveValue performs a merge with any union data inside the Value, using the provided SensitiveValue
func (t *Value) MergeSensitiveValue(v SensitiveValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {

}
