// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const deleteChangelogEntry = `-- name: DeleteChangelogEntry :batchexec
DELETE FROM changelog_entry
WHERE workspace_id = $1 AND entity_type = $2 AND entity_id = $3
`

type DeleteChangelogEntryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteChangelogEntryParams struct {
	WorkspaceID uuid.UUID
	EntityType  string
	EntityID    string
}

func (q *Queries) DeleteChangelogEntry(ctx context.Context, arg []DeleteChangelogEntryParams) *DeleteChangelogEntryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.WorkspaceID,
			a.EntityType,
			a.EntityID,
		}
		batch.Queue(deleteChangelogEntry, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteChangelogEntryBatchResults{br, len(arg), false}
}

func (b *DeleteChangelogEntryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteChangelogEntryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertChangelogEntry = `-- name: UpsertChangelogEntry :batchexec
INSERT INTO changelog_entry (workspace_id, entity_type, entity_id, entity_data, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, entity_type, entity_id)
DO UPDATE SET entity_data = EXCLUDED.entity_data
`

type UpsertChangelogEntryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertChangelogEntryParams struct {
	WorkspaceID uuid.UUID
	EntityType  string
	EntityID    string
	EntityData  []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertChangelogEntry(ctx context.Context, arg []UpsertChangelogEntryParams) *UpsertChangelogEntryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.WorkspaceID,
			a.EntityType,
			a.EntityID,
			a.EntityData,
			a.CreatedAt,
		}
		batch.Queue(upsertChangelogEntry, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertChangelogEntryBatchResults{br, len(arg), false}
}

func (b *UpsertChangelogEntryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertChangelogEntryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
