// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchDeleteComputedEntityRelationshipByPK = `-- name: BatchDeleteComputedEntityRelationshipByPK :batchexec
DELETE FROM computed_entity_relationship
WHERE rule_id = $1
  AND from_entity_type = $2
  AND from_entity_id = $3
  AND to_entity_type = $4
  AND to_entity_id = $5
`

type BatchDeleteComputedEntityRelationshipByPKBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchDeleteComputedEntityRelationshipByPKParams struct {
	RuleID         uuid.UUID
	FromEntityType string
	FromEntityID   uuid.UUID
	ToEntityType   string
	ToEntityID     uuid.UUID
}

func (q *Queries) BatchDeleteComputedEntityRelationshipByPK(ctx context.Context, arg []BatchDeleteComputedEntityRelationshipByPKParams) *BatchDeleteComputedEntityRelationshipByPKBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RuleID,
			a.FromEntityType,
			a.FromEntityID,
			a.ToEntityType,
			a.ToEntityID,
		}
		batch.Queue(batchDeleteComputedEntityRelationshipByPK, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchDeleteComputedEntityRelationshipByPKBatchResults{br, len(arg), false}
}

func (b *BatchDeleteComputedEntityRelationshipByPKBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchDeleteComputedEntityRelationshipByPKBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchDeleteStalePolicyRuleEvaluations = `-- name: BatchDeleteStalePolicyRuleEvaluations :batchexec
DELETE FROM policy_rule_evaluation
WHERE environment_id = $1
  AND version_id = $2
  AND resource_id = $3
  AND rule_type = ANY($4::text[])
  AND rule_id != ALL($5::uuid[])
`

type BatchDeleteStalePolicyRuleEvaluationsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchDeleteStalePolicyRuleEvaluationsParams struct {
	EnvironmentID uuid.UUID
	VersionID     uuid.UUID
	ResourceID    uuid.UUID
	RuleTypes     []string
	KeepRuleIds   []uuid.UUID
}

func (q *Queries) BatchDeleteStalePolicyRuleEvaluations(ctx context.Context, arg []BatchDeleteStalePolicyRuleEvaluationsParams) *BatchDeleteStalePolicyRuleEvaluationsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EnvironmentID,
			a.VersionID,
			a.ResourceID,
			a.RuleTypes,
			a.KeepRuleIds,
		}
		batch.Queue(batchDeleteStalePolicyRuleEvaluations, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchDeleteStalePolicyRuleEvaluationsBatchResults{br, len(arg), false}
}

func (b *BatchDeleteStalePolicyRuleEvaluationsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchDeleteStalePolicyRuleEvaluationsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchUpsertComputedEntityRelationship = `-- name: BatchUpsertComputedEntityRelationship :batchexec
INSERT INTO computed_entity_relationship (
    rule_id, from_entity_type, from_entity_id, to_entity_type, to_entity_id, last_evaluated_at
)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (rule_id, from_entity_type, from_entity_id, to_entity_type, to_entity_id) DO UPDATE
SET last_evaluated_at = NOW()
`

type BatchUpsertComputedEntityRelationshipBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertComputedEntityRelationshipParams struct {
	RuleID         uuid.UUID
	FromEntityType string
	FromEntityID   uuid.UUID
	ToEntityType   string
	ToEntityID     uuid.UUID
}

func (q *Queries) BatchUpsertComputedEntityRelationship(ctx context.Context, arg []BatchUpsertComputedEntityRelationshipParams) *BatchUpsertComputedEntityRelationshipBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RuleID,
			a.FromEntityType,
			a.FromEntityID,
			a.ToEntityType,
			a.ToEntityID,
		}
		batch.Queue(batchUpsertComputedEntityRelationship, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertComputedEntityRelationshipBatchResults{br, len(arg), false}
}

func (b *BatchUpsertComputedEntityRelationshipBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertComputedEntityRelationshipBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchUpsertPolicyRuleEvaluation = `-- name: BatchUpsertPolicyRuleEvaluation :batchexec
INSERT INTO policy_rule_evaluation (
    rule_type, rule_id, environment_id, version_id, resource_id,
    allowed, action_required, action_type, message, details,
    satisfied_at, next_evaluation_at, evaluated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW())
ON CONFLICT (rule_id, environment_id, version_id, resource_id) DO UPDATE
SET rule_type          = EXCLUDED.rule_type,
    allowed            = EXCLUDED.allowed,
    action_required    = EXCLUDED.action_required,
    action_type        = EXCLUDED.action_type,
    message            = EXCLUDED.message,
    details            = EXCLUDED.details,
    satisfied_at       = EXCLUDED.satisfied_at,
    next_evaluation_at = EXCLUDED.next_evaluation_at,
    evaluated_at       = EXCLUDED.evaluated_at
`

type BatchUpsertPolicyRuleEvaluationBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertPolicyRuleEvaluationParams struct {
	RuleType         string
	RuleID           uuid.UUID
	EnvironmentID    uuid.UUID
	VersionID        uuid.UUID
	ResourceID       uuid.UUID
	Allowed          bool
	ActionRequired   bool
	ActionType       pgtype.Text
	Message          string
	Details          map[string]any
	SatisfiedAt      pgtype.Timestamptz
	NextEvaluationAt pgtype.Timestamptz
}

func (q *Queries) BatchUpsertPolicyRuleEvaluation(ctx context.Context, arg []BatchUpsertPolicyRuleEvaluationParams) *BatchUpsertPolicyRuleEvaluationBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.RuleType,
			a.RuleID,
			a.EnvironmentID,
			a.VersionID,
			a.ResourceID,
			a.Allowed,
			a.ActionRequired,
			a.ActionType,
			a.Message,
			a.Details,
			a.SatisfiedAt,
			a.NextEvaluationAt,
		}
		batch.Queue(batchUpsertPolicyRuleEvaluation, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertPolicyRuleEvaluationBatchResults{br, len(arg), false}
}

func (b *BatchUpsertPolicyRuleEvaluationBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertPolicyRuleEvaluationBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchUpsertResource = `-- name: BatchUpsertResource :batchexec
INSERT INTO resource (id, version, name, kind, identifier, provider_id, workspace_id,
                      config, created_at, updated_at, deleted_at, metadata)
VALUES ($1, $2, $3, $4, $5,
        NULLIF($6, '00000000-0000-0000-0000-000000000000'::uuid),
        $7, $8, $9, $10, $11, $12)
ON CONFLICT (workspace_id, identifier) DO UPDATE
SET version = EXCLUDED.version, name = EXCLUDED.name,
    kind = EXCLUDED.kind, provider_id = EXCLUDED.provider_id,
    config = EXCLUDED.config, updated_at = EXCLUDED.updated_at,
    deleted_at = EXCLUDED.deleted_at, metadata = EXCLUDED.metadata
`

type BatchUpsertResourceBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertResourceParams struct {
	ID          uuid.UUID
	Version     string
	Name        string
	Kind        string
	Identifier  string
	ProviderID  uuid.UUID
	WorkspaceID uuid.UUID
	Config      map[string]any
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Metadata    map[string]string
}

func (q *Queries) BatchUpsertResource(ctx context.Context, arg []BatchUpsertResourceParams) *BatchUpsertResourceBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.Version,
			a.Name,
			a.Kind,
			a.Identifier,
			a.ProviderID,
			a.WorkspaceID,
			a.Config,
			a.CreatedAt,
			a.UpdatedAt,
			a.DeletedAt,
			a.Metadata,
		}
		batch.Queue(batchUpsertResource, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertResourceBatchResults{br, len(arg), false}
}

func (b *BatchUpsertResourceBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertResourceBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const deleteChangelogEntry = `-- name: DeleteChangelogEntry :batchexec
DELETE FROM changelog_entry
WHERE workspace_id = $1 AND entity_type = $2 AND entity_id = $3
`

type DeleteChangelogEntryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type DeleteChangelogEntryParams struct {
	WorkspaceID uuid.UUID
	EntityType  string
	EntityID    string
}

func (q *Queries) DeleteChangelogEntry(ctx context.Context, arg []DeleteChangelogEntryParams) *DeleteChangelogEntryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.WorkspaceID,
			a.EntityType,
			a.EntityID,
		}
		batch.Queue(deleteChangelogEntry, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &DeleteChangelogEntryBatchResults{br, len(arg), false}
}

func (b *DeleteChangelogEntryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *DeleteChangelogEntryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertChangelogEntry = `-- name: UpsertChangelogEntry :batchexec
INSERT INTO changelog_entry (workspace_id, entity_type, entity_id, entity_data, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, entity_type, entity_id)
DO UPDATE SET entity_data = EXCLUDED.entity_data
`

type UpsertChangelogEntryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertChangelogEntryParams struct {
	WorkspaceID uuid.UUID
	EntityType  string
	EntityID    string
	EntityData  []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertChangelogEntry(ctx context.Context, arg []UpsertChangelogEntryParams) *UpsertChangelogEntryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.WorkspaceID,
			a.EntityType,
			a.EntityID,
			a.EntityData,
			a.CreatedAt,
		}
		batch.Queue(upsertChangelogEntry, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertChangelogEntryBatchResults{br, len(arg), false}
}

func (b *UpsertChangelogEntryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertChangelogEntryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
