// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: computed_resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getReleaseTargetsForDeployment = `-- name: GetReleaseTargetsForDeployment :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cdr.deployment_id = $1
`

type GetReleaseTargetsForDeploymentRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all valid release targets for a deployment by joining computed
// resource tables through the system link tables.
func (q *Queries) GetReleaseTargetsForDeployment(ctx context.Context, deploymentID uuid.UUID) ([]GetReleaseTargetsForDeploymentRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForDeploymentRow
	for rows.Next() {
		var i GetReleaseTargetsForDeploymentRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTargetExists = `-- name: ReleaseTargetExists :one
SELECT EXISTS (
    SELECT 1
    FROM computed_deployment_resource cdr
    JOIN computed_environment_resource cer
        ON cer.resource_id = cdr.resource_id
    JOIN system_deployment sd
        ON sd.deployment_id = cdr.deployment_id
    JOIN system_environment se
        ON se.environment_id = cer.environment_id
        AND se.system_id = sd.system_id
    WHERE cdr.deployment_id = $1
      AND cer.environment_id = $2
      AND cdr.resource_id = $3
) AS exists
`

type ReleaseTargetExistsParams struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Checks whether a specific (deployment, environment, resource) triple forms
// a valid release target via the computed resource and system link tables.
func (q *Queries) ReleaseTargetExists(ctx context.Context, arg ReleaseTargetExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, releaseTargetExists, arg.DeploymentID, arg.EnvironmentID, arg.ResourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setComputedDeploymentResources = `-- name: SetComputedDeploymentResources :exec
WITH current AS (
    SELECT unnest($2::uuid[]) AS resource_id
),
deleted AS (
    DELETE FROM computed_deployment_resource
    WHERE deployment_id = $1
      AND resource_id NOT IN (SELECT resource_id FROM current)
)
INSERT INTO computed_deployment_resource (deployment_id, resource_id, last_evaluated_at)
SELECT $1, resource_id, NOW()
FROM current
ON CONFLICT (deployment_id, resource_id) DO UPDATE
SET last_evaluated_at = NOW()
`

type SetComputedDeploymentResourcesParams struct {
	DeploymentID uuid.UUID
	ResourceIds  []uuid.UUID
}

// Replaces the full set of computed resources for a deployment.
// Deletes stale rows and upserts the current set with last_evaluated_at = NOW().
func (q *Queries) SetComputedDeploymentResources(ctx context.Context, arg SetComputedDeploymentResourcesParams) error {
	_, err := q.db.Exec(ctx, setComputedDeploymentResources, arg.DeploymentID, arg.ResourceIds)
	return err
}

const setComputedEnvironmentResources = `-- name: SetComputedEnvironmentResources :exec
WITH current AS (
    SELECT unnest($2::uuid[]) AS resource_id
),
deleted AS (
    DELETE FROM computed_environment_resource
    WHERE environment_id = $1
      AND resource_id NOT IN (SELECT resource_id FROM current)
)
INSERT INTO computed_environment_resource (environment_id, resource_id, last_evaluated_at)
SELECT $1, resource_id, NOW()
FROM current
ON CONFLICT (environment_id, resource_id) DO UPDATE
SET last_evaluated_at = NOW()
`

type SetComputedEnvironmentResourcesParams struct {
	EnvironmentID uuid.UUID
	ResourceIds   []uuid.UUID
}

// Replaces the full set of computed resources for an environment.
// Deletes stale rows and upserts the current set with last_evaluated_at = NOW().
func (q *Queries) SetComputedEnvironmentResources(ctx context.Context, arg SetComputedEnvironmentResourcesParams) error {
	_, err := q.db.Exec(ctx, setComputedEnvironmentResources, arg.EnvironmentID, arg.ResourceIds)
	return err
}
