// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: computed_resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getReleaseTargetForDeploymentResource = `-- name: GetReleaseTargetForDeploymentResource :one
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cdr.deployment_id = $1
  AND cdr.resource_id = $2
LIMIT 1
`

type GetReleaseTargetForDeploymentResourceParams struct {
	DeploymentID uuid.UUID
	ResourceID   uuid.UUID
}

type GetReleaseTargetForDeploymentResourceRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns one release target for a (deployment, resource) pair across any
// environment. Used by the deployment-version-dependency evaluator, which
// only needs to identify some environment in which the dependency lives.
func (q *Queries) GetReleaseTargetForDeploymentResource(ctx context.Context, arg GetReleaseTargetForDeploymentResourceParams) (GetReleaseTargetForDeploymentResourceRow, error) {
	row := q.db.QueryRow(ctx, getReleaseTargetForDeploymentResource, arg.DeploymentID, arg.ResourceID)
	var i GetReleaseTargetForDeploymentResourceRow
	err := row.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID)
	return i, err
}

const getReleaseTargetsForDeployment = `-- name: GetReleaseTargetsForDeployment :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cdr.deployment_id = $1
`

type GetReleaseTargetsForDeploymentRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all valid release targets for a deployment by joining computed
// resource tables through the system link tables.
func (q *Queries) GetReleaseTargetsForDeployment(ctx context.Context, deploymentID uuid.UUID) ([]GetReleaseTargetsForDeploymentRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForDeploymentRow
	for rows.Next() {
		var i GetReleaseTargetsForDeploymentRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseTargetsForDeploymentAndEnvironment = `-- name: GetReleaseTargetsForDeploymentAndEnvironment :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cdr.deployment_id = $1
  AND cer.environment_id = $2
`

type GetReleaseTargetsForDeploymentAndEnvironmentParams struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
}

type GetReleaseTargetsForDeploymentAndEnvironmentRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all valid release targets for a deployment and environment pair.
func (q *Queries) GetReleaseTargetsForDeploymentAndEnvironment(ctx context.Context, arg GetReleaseTargetsForDeploymentAndEnvironmentParams) ([]GetReleaseTargetsForDeploymentAndEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForDeploymentAndEnvironment, arg.DeploymentID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForDeploymentAndEnvironmentRow
	for rows.Next() {
		var i GetReleaseTargetsForDeploymentAndEnvironmentRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseTargetsForDeploymentAndResource = `-- name: GetReleaseTargetsForDeploymentAndResource :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cdr.deployment_id = $1
  AND cdr.resource_id = $2
`

type GetReleaseTargetsForDeploymentAndResourceParams struct {
	DeploymentID uuid.UUID
	ResourceID   uuid.UUID
}

type GetReleaseTargetsForDeploymentAndResourceRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all release targets for a (deployment, resource) pair across every
// environment in which the deployment-resource combination is valid. Used by
// the dependency-downstream dispatcher to fan out reconciliation events to
// every downstream release target on the same resource.
func (q *Queries) GetReleaseTargetsForDeploymentAndResource(ctx context.Context, arg GetReleaseTargetsForDeploymentAndResourceParams) ([]GetReleaseTargetsForDeploymentAndResourceRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForDeploymentAndResource, arg.DeploymentID, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForDeploymentAndResourceRow
	for rows.Next() {
		var i GetReleaseTargetsForDeploymentAndResourceRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseTargetsForEnvironment = `-- name: GetReleaseTargetsForEnvironment :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cer.environment_id = $1
`

type GetReleaseTargetsForEnvironmentRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all valid release targets for an environment by joining computed
// resource tables through the system link tables.
func (q *Queries) GetReleaseTargetsForEnvironment(ctx context.Context, environmentID uuid.UUID) ([]GetReleaseTargetsForEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForEnvironmentRow
	for rows.Next() {
		var i GetReleaseTargetsForEnvironmentRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseTargetsForEnvironments = `-- name: GetReleaseTargetsForEnvironments :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cer.environment_id = ANY($1::uuid[])
`

type GetReleaseTargetsForEnvironmentsRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all valid release targets for a set of environments.
func (q *Queries) GetReleaseTargetsForEnvironments(ctx context.Context, environmentIds []uuid.UUID) ([]GetReleaseTargetsForEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForEnvironments, environmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForEnvironmentsRow
	for rows.Next() {
		var i GetReleaseTargetsForEnvironmentsRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseTargetsForResource = `-- name: GetReleaseTargetsForResource :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
WHERE cdr.resource_id = $1
`

type GetReleaseTargetsForResourceRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all valid release targets for a resource by joining computed
// resource tables through the system link tables.
func (q *Queries) GetReleaseTargetsForResource(ctx context.Context, resourceID uuid.UUID) ([]GetReleaseTargetsForResourceRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForResourceRow
	for rows.Next() {
		var i GetReleaseTargetsForResourceRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseTargetsForWorkspace = `-- name: GetReleaseTargetsForWorkspace :many
SELECT DISTINCT
    cdr.deployment_id,
    cer.environment_id,
    cdr.resource_id
FROM computed_deployment_resource cdr
JOIN computed_environment_resource cer
    ON cer.resource_id = cdr.resource_id
JOIN system_deployment sd
    ON sd.deployment_id = cdr.deployment_id
JOIN system_environment se
    ON se.environment_id = cer.environment_id
    AND se.system_id = sd.system_id
JOIN deployment d
    ON d.id = cdr.deployment_id
WHERE d.workspace_id = $1
`

type GetReleaseTargetsForWorkspaceRow struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Returns all valid release targets for a workspace.
func (q *Queries) GetReleaseTargetsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]GetReleaseTargetsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, getReleaseTargetsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReleaseTargetsForWorkspaceRow
	for rows.Next() {
		var i GetReleaseTargetsForWorkspaceRow
		if err := rows.Scan(&i.DeploymentID, &i.EnvironmentID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTargetExists = `-- name: ReleaseTargetExists :one
SELECT EXISTS (
    SELECT 1
    FROM computed_deployment_resource cdr
    JOIN computed_environment_resource cer
        ON cer.resource_id = cdr.resource_id
    JOIN system_deployment sd
        ON sd.deployment_id = cdr.deployment_id
    JOIN system_environment se
        ON se.environment_id = cer.environment_id
        AND se.system_id = sd.system_id
    WHERE cdr.deployment_id = $1
      AND cer.environment_id = $2
      AND cdr.resource_id = $3
) AS exists
`

type ReleaseTargetExistsParams struct {
	DeploymentID  uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

// Checks whether a specific (deployment, environment, resource) triple forms
// a valid release target via the computed resource and system link tables.
func (q *Queries) ReleaseTargetExists(ctx context.Context, arg ReleaseTargetExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, releaseTargetExists, arg.DeploymentID, arg.EnvironmentID, arg.ResourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setComputedDeploymentResources = `-- name: SetComputedDeploymentResources :exec
WITH current AS (
    SELECT unnest($2::uuid[]) AS resource_id
),
valid AS (
    SELECT c.resource_id
    FROM current c
    JOIN resource r ON r.id = c.resource_id
),
deleted AS (
    DELETE FROM computed_deployment_resource
    WHERE deployment_id = $1
      AND resource_id NOT IN (SELECT resource_id FROM valid)
)
INSERT INTO computed_deployment_resource (deployment_id, resource_id, last_evaluated_at)
SELECT $1, resource_id, NOW()
FROM valid
ON CONFLICT (deployment_id, resource_id) DO NOTHING
`

type SetComputedDeploymentResourcesParams struct {
	DeploymentID uuid.UUID
	ResourceIds  []uuid.UUID
}

// Replaces the full set of computed resources for a deployment.
// Deletes stale rows and upserts the current set with last_evaluated_at = NOW().
// The valid CTE filters against the resource table to avoid FK violations from
// resources deleted between selector evaluation and this write.
func (q *Queries) SetComputedDeploymentResources(ctx context.Context, arg SetComputedDeploymentResourcesParams) error {
	_, err := q.db.Exec(ctx, setComputedDeploymentResources, arg.DeploymentID, arg.ResourceIds)
	return err
}

const setComputedEnvironmentResources = `-- name: SetComputedEnvironmentResources :exec
WITH current AS (
    SELECT unnest($2::uuid[]) AS resource_id
),
valid AS (
    SELECT c.resource_id
    FROM current c
    JOIN resource r ON r.id = c.resource_id
),
deleted AS (
    DELETE FROM computed_environment_resource
    WHERE environment_id = $1
      AND resource_id NOT IN (SELECT resource_id FROM valid)
)
INSERT INTO computed_environment_resource (environment_id, resource_id, last_evaluated_at)
SELECT $1, resource_id, NOW()
FROM valid
ON CONFLICT (environment_id, resource_id) DO NOTHING
`

type SetComputedEnvironmentResourcesParams struct {
	EnvironmentID uuid.UUID
	ResourceIds   []uuid.UUID
}

// Replaces the full set of computed resources for an environment.
// Deletes stale rows and upserts the current set with last_evaluated_at = NOW().
// The valid CTE filters against the resource table to avoid FK violations from
// resources deleted between selector evaluation and this write.
func (q *Queries) SetComputedEnvironmentResources(ctx context.Context, arg SetComputedEnvironmentResourcesParams) error {
	_, err := q.db.Exec(ctx, setComputedEnvironmentResources, arg.EnvironmentID, arg.ResourceIds)
	return err
}
