// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: computed_relationships.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bulkUpsertComputedRelationships = `-- name: BulkUpsertComputedRelationships :exec
INSERT INTO computed_entity_relationship (
    rule_id, from_entity_type, from_entity_id, to_entity_type, to_entity_id, last_evaluated_at
)
SELECT
    unnest($1::uuid[]) AS rule_id,
    unnest($2::text[]) AS from_entity_type,
    unnest($3::uuid[]) AS from_entity_id,
    unnest($4::text[]) AS to_entity_type,
    unnest($5::uuid[]) AS to_entity_id,
    NOW()
ON CONFLICT (rule_id, from_entity_type, from_entity_id, to_entity_type, to_entity_id) DO UPDATE
SET last_evaluated_at = NOW()
`

type BulkUpsertComputedRelationshipsParams struct {
	RuleIds         []uuid.UUID
	FromEntityTypes []string
	FromEntityIds   []uuid.UUID
	ToEntityTypes   []string
	ToEntityIds     []uuid.UUID
}

// Inserts many computed relationships in one query, updating last_evaluated_at on conflict.
func (q *Queries) BulkUpsertComputedRelationships(ctx context.Context, arg BulkUpsertComputedRelationshipsParams) error {
	_, err := q.db.Exec(ctx, bulkUpsertComputedRelationships,
		arg.RuleIds,
		arg.FromEntityTypes,
		arg.FromEntityIds,
		arg.ToEntityTypes,
		arg.ToEntityIds,
	)
	return err
}

const deleteComputedRelationshipsForEntity = `-- name: DeleteComputedRelationshipsForEntity :exec
DELETE FROM computed_entity_relationship
WHERE (from_entity_type = $1 AND from_entity_id = $2)
   OR (to_entity_type = $1 AND to_entity_id = $2)
`

type DeleteComputedRelationshipsForEntityParams struct {
	EntityType string
	EntityID   uuid.UUID
}

// Removes all computed relationships where the given entity appears
// as either the "from" or "to" side.
func (q *Queries) DeleteComputedRelationshipsForEntity(ctx context.Context, arg DeleteComputedRelationshipsForEntityParams) error {
	_, err := q.db.Exec(ctx, deleteComputedRelationshipsForEntity, arg.EntityType, arg.EntityID)
	return err
}

const getRelationshipRulesForWorkspace = `-- name: GetRelationshipRulesForWorkspace :many
SELECT id, reference, cel
FROM relationship_rule
WHERE workspace_id = $1
`

type GetRelationshipRulesForWorkspaceRow struct {
	ID        uuid.UUID
	Reference string
	Cel       string
}

// Returns all relationship rules for a workspace.
func (q *Queries) GetRelationshipRulesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]GetRelationshipRulesForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, getRelationshipRulesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelationshipRulesForWorkspaceRow
	for rows.Next() {
		var i GetRelationshipRulesForWorkspaceRow
		if err := rows.Scan(&i.ID, &i.Reference, &i.Cel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComputedRelationship = `-- name: UpsertComputedRelationship :exec
INSERT INTO computed_entity_relationship (
    rule_id, from_entity_type, from_entity_id, to_entity_type, to_entity_id, last_evaluated_at
)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (rule_id, from_entity_type, from_entity_id, to_entity_type, to_entity_id) DO UPDATE
SET last_evaluated_at = NOW()
`

type UpsertComputedRelationshipParams struct {
	RuleID         uuid.UUID
	FromEntityType string
	FromEntityID   uuid.UUID
	ToEntityType   string
	ToEntityID     uuid.UUID
}

// Inserts a computed relationship or updates last_evaluated_at if it already exists.
func (q *Queries) UpsertComputedRelationship(ctx context.Context, arg UpsertComputedRelationshipParams) error {
	_, err := q.db.Exec(ctx, upsertComputedRelationship,
		arg.RuleID,
		arg.FromEntityType,
		arg.FromEntityID,
		arg.ToEntityType,
		arg.ToEntityID,
	)
	return err
}
