// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_plan.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeploymentPlan = `-- name: GetDeploymentPlan :one
SELECT
  dp.id,
  dp.workspace_id,
  dp.deployment_id,
  dp.version_tag,
  dp.version_name,
  dp.version_config,
  dp.version_job_agent_config,
  dp.version_metadata,
  dp.metadata,
  dp.created_at,
  dp.completed_at,
  dp.expires_at
FROM deployment_plan dp
WHERE dp.id = $1
`

func (q *Queries) GetDeploymentPlan(ctx context.Context, id uuid.UUID) (DeploymentPlan, error) {
	row := q.db.QueryRow(ctx, getDeploymentPlan, id)
	var i DeploymentPlan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DeploymentID,
		&i.VersionTag,
		&i.VersionName,
		&i.VersionConfig,
		&i.VersionJobAgentConfig,
		&i.VersionMetadata,
		&i.Metadata,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getDeploymentPlanTargetResult = `-- name: GetDeploymentPlanTargetResult :one
SELECT
  r.id,
  r.target_id,
  r.dispatch_context,
  r.agent_state,
  r.status,
  r.has_changes,
  r.content_hash,
  r.current,
  r.proposed,
  r.message,
  r.started_at,
  r.completed_at
FROM deployment_plan_target_result r
WHERE r.id = $1
`

func (q *Queries) GetDeploymentPlanTargetResult(ctx context.Context, id uuid.UUID) (DeploymentPlanTargetResult, error) {
	row := q.db.QueryRow(ctx, getDeploymentPlanTargetResult, id)
	var i DeploymentPlanTargetResult
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.DispatchContext,
		&i.AgentState,
		&i.Status,
		&i.HasChanges,
		&i.ContentHash,
		&i.Current,
		&i.Proposed,
		&i.Message,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTargetContextByResultID = `-- name: GetTargetContextByResultID :one
SELECT
  t.id AS target_id,
  t.plan_id,
  t.current_release_id,
  dp.deployment_id,
  dp.workspace_id,
  dp.version_tag,
  dp.version_metadata,
  w.slug AS workspace_slug,
  e.name AS environment_name,
  res.name AS resource_name
FROM deployment_plan_target_result r
JOIN deployment_plan_target t ON t.id = r.target_id
JOIN deployment_plan dp ON dp.id = t.plan_id
JOIN workspace w ON w.id = dp.workspace_id
JOIN environment e ON e.id = t.environment_id
JOIN resource res ON res.id = t.resource_id
WHERE r.id = $1
`

type GetTargetContextByResultIDRow struct {
	TargetID         uuid.UUID
	PlanID           uuid.UUID
	CurrentReleaseID pgtype.UUID
	DeploymentID     uuid.UUID
	WorkspaceID      uuid.UUID
	VersionTag       string
	VersionMetadata  map[string]string
	WorkspaceSlug    string
	EnvironmentName  string
	ResourceName     string
}

func (q *Queries) GetTargetContextByResultID(ctx context.Context, id uuid.UUID) (GetTargetContextByResultIDRow, error) {
	row := q.db.QueryRow(ctx, getTargetContextByResultID, id)
	var i GetTargetContextByResultIDRow
	err := row.Scan(
		&i.TargetID,
		&i.PlanID,
		&i.CurrentReleaseID,
		&i.DeploymentID,
		&i.WorkspaceID,
		&i.VersionTag,
		&i.VersionMetadata,
		&i.WorkspaceSlug,
		&i.EnvironmentName,
		&i.ResourceName,
	)
	return i, err
}

const insertDeploymentPlanTarget = `-- name: InsertDeploymentPlanTarget :one
INSERT INTO deployment_plan_target (id, plan_id, environment_id, resource_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (plan_id, environment_id, resource_id) DO NOTHING
RETURNING id
`

type InsertDeploymentPlanTargetParams struct {
	ID            uuid.UUID
	PlanID        uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

func (q *Queries) InsertDeploymentPlanTarget(ctx context.Context, arg InsertDeploymentPlanTargetParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDeploymentPlanTarget,
		arg.ID,
		arg.PlanID,
		arg.EnvironmentID,
		arg.ResourceID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertDeploymentPlanTargetResult = `-- name: InsertDeploymentPlanTargetResult :exec
INSERT INTO deployment_plan_target_result (id, target_id, dispatch_context, status)
VALUES ($1, $2, $3, 'computing')
`

type InsertDeploymentPlanTargetResultParams struct {
	ID              uuid.UUID
	TargetID        uuid.UUID
	DispatchContext []byte
}

func (q *Queries) InsertDeploymentPlanTargetResult(ctx context.Context, arg InsertDeploymentPlanTargetResultParams) error {
	_, err := q.db.Exec(ctx, insertDeploymentPlanTargetResult, arg.ID, arg.TargetID, arg.DispatchContext)
	return err
}

const listDeploymentPlanTargetResultsByTargetID = `-- name: ListDeploymentPlanTargetResultsByTargetID :many
SELECT
  r.id,
  r.target_id,
  r.dispatch_context,
  r.status,
  r.has_changes,
  r.current,
  r.proposed,
  r.message,
  r.started_at,
  r.completed_at
FROM deployment_plan_target_result r
WHERE r.target_id = $1
ORDER BY r.started_at
`

type ListDeploymentPlanTargetResultsByTargetIDRow struct {
	ID              uuid.UUID
	TargetID        uuid.UUID
	DispatchContext []byte
	Status          DeploymentPlanTargetStatus
	HasChanges      pgtype.Bool
	Current         pgtype.Text
	Proposed        pgtype.Text
	Message         pgtype.Text
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
}

func (q *Queries) ListDeploymentPlanTargetResultsByTargetID(ctx context.Context, targetID uuid.UUID) ([]ListDeploymentPlanTargetResultsByTargetIDRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentPlanTargetResultsByTargetID, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentPlanTargetResultsByTargetIDRow
	for rows.Next() {
		var i ListDeploymentPlanTargetResultsByTargetIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.DispatchContext,
			&i.Status,
			&i.HasChanges,
			&i.Current,
			&i.Proposed,
			&i.Message,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentPlanCompleted = `-- name: UpdateDeploymentPlanCompleted :exec
UPDATE deployment_plan
SET completed_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateDeploymentPlanCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateDeploymentPlanCompleted, id)
	return err
}

const updateDeploymentPlanTargetResultCompleted = `-- name: UpdateDeploymentPlanTargetResultCompleted :exec
UPDATE deployment_plan_target_result
SET status = $2,
    has_changes = $3,
    content_hash = $4,
    current = $5,
    proposed = $6,
    message = $7,
    completed_at = NOW()
WHERE id = $1
`

type UpdateDeploymentPlanTargetResultCompletedParams struct {
	ID          uuid.UUID
	Status      DeploymentPlanTargetStatus
	HasChanges  pgtype.Bool
	ContentHash pgtype.Text
	Current     pgtype.Text
	Proposed    pgtype.Text
	Message     pgtype.Text
}

func (q *Queries) UpdateDeploymentPlanTargetResultCompleted(ctx context.Context, arg UpdateDeploymentPlanTargetResultCompletedParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentPlanTargetResultCompleted,
		arg.ID,
		arg.Status,
		arg.HasChanges,
		arg.ContentHash,
		arg.Current,
		arg.Proposed,
		arg.Message,
	)
	return err
}

const updateDeploymentPlanTargetResultState = `-- name: UpdateDeploymentPlanTargetResultState :exec
UPDATE deployment_plan_target_result
SET agent_state = $2
WHERE id = $1
`

type UpdateDeploymentPlanTargetResultStateParams struct {
	ID         uuid.UUID
	AgentState []byte
}

func (q *Queries) UpdateDeploymentPlanTargetResultState(ctx context.Context, arg UpdateDeploymentPlanTargetResultStateParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentPlanTargetResultState, arg.ID, arg.AgentState)
	return err
}
