// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_versions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeploymentVersion = `-- name: DeleteDeploymentVersion :exec
DELETE FROM deployment_version WHERE id = $1
`

func (q *Queries) DeleteDeploymentVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeploymentVersion, id)
	return err
}

const getDeploymentVersionByID = `-- name: GetDeploymentVersionByID :one
SELECT id, name, tag, config, job_agent_config, deployment_id, status, message, created_at, workspace_id FROM deployment_version WHERE id = $1
`

func (q *Queries) GetDeploymentVersionByID(ctx context.Context, id uuid.UUID) (DeploymentVersion, error) {
	row := q.db.QueryRow(ctx, getDeploymentVersionByID, id)
	var i DeploymentVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.Config,
		&i.JobAgentConfig,
		&i.DeploymentID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listDeploymentVersionsByDeploymentID = `-- name: ListDeploymentVersionsByDeploymentID :many
SELECT id, name, tag, config, job_agent_config, deployment_id, status, message, created_at, workspace_id FROM deployment_version WHERE deployment_id = $1 ORDER BY created_at DESC
LIMIT COALESCE($2::int, 5000)
`

type ListDeploymentVersionsByDeploymentIDParams struct {
	DeploymentID uuid.UUID
	Limit        pgtype.Int4
}

func (q *Queries) ListDeploymentVersionsByDeploymentID(ctx context.Context, arg ListDeploymentVersionsByDeploymentIDParams) ([]DeploymentVersion, error) {
	rows, err := q.db.Query(ctx, listDeploymentVersionsByDeploymentID, arg.DeploymentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentVersion
	for rows.Next() {
		var i DeploymentVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Config,
			&i.JobAgentConfig,
			&i.DeploymentID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentVersionsByWorkspaceID = `-- name: ListDeploymentVersionsByWorkspaceID :many
SELECT id, name, tag, config, job_agent_config, deployment_id, status, message, created_at, workspace_id FROM deployment_version
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT COALESCE($2::int, 5000)
`

type ListDeploymentVersionsByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
	Limit       pgtype.Int4
}

func (q *Queries) ListDeploymentVersionsByWorkspaceID(ctx context.Context, arg ListDeploymentVersionsByWorkspaceIDParams) ([]DeploymentVersion, error) {
	rows, err := q.db.Query(ctx, listDeploymentVersionsByWorkspaceID, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentVersion
	for rows.Next() {
		var i DeploymentVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Config,
			&i.JobAgentConfig,
			&i.DeploymentID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeploymentVersion = `-- name: UpsertDeploymentVersion :one
INSERT INTO deployment_version (name, tag, config, job_agent_config, deployment_id, status, message, workspace_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9::timestamptz, NOW()))
ON CONFLICT (deployment_id, tag) DO UPDATE
SET name = EXCLUDED.name, config = EXCLUDED.config, job_agent_config = EXCLUDED.job_agent_config, status = EXCLUDED.status, message = EXCLUDED.message, workspace_id = EXCLUDED.workspace_id,
    created_at = CASE WHEN $9::timestamptz IS NOT NULL THEN EXCLUDED.created_at ELSE deployment_version.created_at END
RETURNING id, name, tag, config, job_agent_config, deployment_id, status, message, created_at, workspace_id
`

type UpsertDeploymentVersionParams struct {
	Name           string
	Tag            string
	Config         []byte
	JobAgentConfig []byte
	DeploymentID   uuid.UUID
	Status         DeploymentVersionStatus
	Message        pgtype.Text
	WorkspaceID    uuid.UUID
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertDeploymentVersion(ctx context.Context, arg UpsertDeploymentVersionParams) (DeploymentVersion, error) {
	row := q.db.QueryRow(ctx, upsertDeploymentVersion,
		arg.Name,
		arg.Tag,
		arg.Config,
		arg.JobAgentConfig,
		arg.DeploymentID,
		arg.Status,
		arg.Message,
		arg.WorkspaceID,
		arg.CreatedAt,
	)
	var i DeploymentVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.Config,
		&i.JobAgentConfig,
		&i.DeploymentID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}
