// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployment WHERE id = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeployment, id)
	return err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT
    d.id,
    d.name,
    d.description,
    d.job_agent_id,
    d.job_agent_config,
    d.resource_selector,
    d.metadata,
    d.workspace_id,
    sd.system_id
FROM deployment d
LEFT JOIN system_deployment sd ON sd.deployment_id = d.id
WHERE d.id = $1
`

type GetDeploymentByIDRow struct {
	ID               uuid.UUID
	Name             string
	Description      pgtype.Text
	JobAgentID       uuid.UUID
	JobAgentConfig   map[string]any
	ResourceSelector string
	Metadata         map[string]string
	WorkspaceID      uuid.UUID
	SystemID         uuid.UUID
}

func (q *Queries) GetDeploymentByID(ctx context.Context, id uuid.UUID) (GetDeploymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i GetDeploymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.JobAgentID,
		&i.JobAgentConfig,
		&i.ResourceSelector,
		&i.Metadata,
		&i.WorkspaceID,
		&i.SystemID,
	)
	return i, err
}

const listDeploymentsByWorkspaceID = `-- name: ListDeploymentsByWorkspaceID :many
SELECT
    d.id,
    d.name,
    d.description,
    d.job_agent_id,
    d.job_agent_config,
    d.resource_selector,
    d.metadata,
    d.workspace_id,
    sd.system_id
FROM deployment d
LEFT JOIN system_deployment sd ON sd.deployment_id = d.id
WHERE d.workspace_id = $1
LIMIT COALESCE($2::int, 5000)
`

type ListDeploymentsByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
	Limit       pgtype.Int4
}

type ListDeploymentsByWorkspaceIDRow struct {
	ID               uuid.UUID
	Name             string
	Description      pgtype.Text
	JobAgentID       uuid.UUID
	JobAgentConfig   map[string]any
	ResourceSelector string
	Metadata         map[string]string
	WorkspaceID      uuid.UUID
	SystemID         uuid.UUID
}

func (q *Queries) ListDeploymentsByWorkspaceID(ctx context.Context, arg ListDeploymentsByWorkspaceIDParams) ([]ListDeploymentsByWorkspaceIDRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByWorkspaceID, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentsByWorkspaceIDRow
	for rows.Next() {
		var i ListDeploymentsByWorkspaceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.JobAgentID,
			&i.JobAgentConfig,
			&i.ResourceSelector,
			&i.Metadata,
			&i.WorkspaceID,
			&i.SystemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeployment = `-- name: UpsertDeployment :one
INSERT INTO deployment (id, name, description, job_agent_id, job_agent_config, resource_selector, metadata, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, description = EXCLUDED.description, job_agent_id = EXCLUDED.job_agent_id,
    job_agent_config = EXCLUDED.job_agent_config, resource_selector = EXCLUDED.resource_selector,
    metadata = EXCLUDED.metadata, workspace_id = EXCLUDED.workspace_id
RETURNING id, name, description, job_agent_id, job_agent_config, resource_selector, metadata, workspace_id
`

type UpsertDeploymentParams struct {
	ID               uuid.UUID
	Name             string
	Description      pgtype.Text
	JobAgentID       uuid.UUID
	JobAgentConfig   map[string]any
	ResourceSelector string
	Metadata         map[string]string
	WorkspaceID      uuid.UUID
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, upsertDeployment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.JobAgentID,
		arg.JobAgentConfig,
		arg.ResourceSelector,
		arg.Metadata,
		arg.WorkspaceID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.JobAgentID,
		&i.JobAgentConfig,
		&i.ResourceSelector,
		&i.Metadata,
		&i.WorkspaceID,
	)
	return i, err
}

const upsertSystemDeployment = `-- name: UpsertSystemDeployment :exec
INSERT INTO system_deployment (system_id, deployment_id)
VALUES ($1, $2)
ON CONFLICT (system_id, deployment_id) DO NOTHING
`

type UpsertSystemDeploymentParams struct {
	SystemID     uuid.UUID
	DeploymentID uuid.UUID
}

func (q *Queries) UpsertSystemDeployment(ctx context.Context, arg UpsertSystemDeploymentParams) error {
	_, err := q.db.Exec(ctx, upsertSystemDeployment, arg.SystemID, arg.DeploymentID)
	return err
}
