// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_versions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeploymentVersion = `-- name: DeleteDeploymentVersion :exec
DELETE FROM deployment_version WHERE id = $1
`

func (q *Queries) DeleteDeploymentVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeploymentVersion, id)
	return err
}

const getDeploymentVersionByID = `-- name: GetDeploymentVersionByID :one
SELECT id, name, tag, config, job_agent_config, deployment_id, status, message, created_at FROM deployment_version WHERE id = $1
`

func (q *Queries) GetDeploymentVersionByID(ctx context.Context, id uuid.UUID) (DeploymentVersion, error) {
	row := q.db.QueryRow(ctx, getDeploymentVersionByID, id)
	var i DeploymentVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.Config,
		&i.JobAgentConfig,
		&i.DeploymentID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentVersionsByDeploymentID = `-- name: ListDeploymentVersionsByDeploymentID :many
SELECT id, name, tag, config, job_agent_config, deployment_id, status, message, created_at FROM deployment_version WHERE deployment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentVersionsByDeploymentID(ctx context.Context, deploymentID uuid.UUID) ([]DeploymentVersion, error) {
	rows, err := q.db.Query(ctx, listDeploymentVersionsByDeploymentID, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentVersion
	for rows.Next() {
		var i DeploymentVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Config,
			&i.JobAgentConfig,
			&i.DeploymentID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentVersionsByWorkspaceID = `-- name: ListDeploymentVersionsByWorkspaceID :many
SELECT dv.id, dv.name, dv.tag, dv.config, dv.job_agent_config, dv.deployment_id, dv.status, dv.message, dv.created_at FROM deployment_version dv
JOIN deployment d ON dv.deployment_id = d.id
JOIN system s ON d.system_id = s.id
WHERE s.workspace_id = $1
ORDER BY dv.created_at DESC
`

func (q *Queries) ListDeploymentVersionsByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]DeploymentVersion, error) {
	rows, err := q.db.Query(ctx, listDeploymentVersionsByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentVersion
	for rows.Next() {
		var i DeploymentVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Config,
			&i.JobAgentConfig,
			&i.DeploymentID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeploymentVersion = `-- name: UpsertDeploymentVersion :one
INSERT INTO deployment_version (name, tag, config, job_agent_config, deployment_id, status, message)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (deployment_id, tag) DO UPDATE
SET name = EXCLUDED.name, config = EXCLUDED.config, job_agent_config = EXCLUDED.job_agent_config, status = EXCLUDED.status, message = EXCLUDED.message
RETURNING id, name, tag, config, job_agent_config, deployment_id, status, message, created_at
`

type UpsertDeploymentVersionParams struct {
	Name           string
	Tag            string
	Config         []byte
	JobAgentConfig []byte
	DeploymentID   uuid.UUID
	Status         DeploymentVersionStatus
	Message        pgtype.Text
}

func (q *Queries) UpsertDeploymentVersion(ctx context.Context, arg UpsertDeploymentVersionParams) (DeploymentVersion, error) {
	row := q.db.QueryRow(ctx, upsertDeploymentVersion,
		arg.Name,
		arg.Tag,
		arg.Config,
		arg.JobAgentConfig,
		arg.DeploymentID,
		arg.Status,
		arg.Message,
	)
	var i DeploymentVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.Config,
		&i.JobAgentConfig,
		&i.DeploymentID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
