// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteJobAgent = `-- name: DeleteJobAgent :exec
DELETE FROM job_agent WHERE id = $1
`

func (q *Queries) DeleteJobAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobAgent, id)
	return err
}

const getJobAgentByID = `-- name: GetJobAgentByID :one
SELECT id, workspace_id, name, type, config FROM job_agent WHERE id = $1
`

func (q *Queries) GetJobAgentByID(ctx context.Context, id uuid.UUID) (JobAgent, error) {
	row := q.db.QueryRow(ctx, getJobAgentByID, id)
	var i JobAgent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Config,
	)
	return i, err
}

const listJobAgentsByWorkspaceID = `-- name: ListJobAgentsByWorkspaceID :many
SELECT id, workspace_id, name, type, config
FROM job_agent
WHERE workspace_id = $1
`

func (q *Queries) ListJobAgentsByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]JobAgent, error) {
	rows, err := q.db.Query(ctx, listJobAgentsByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobAgent
	for rows.Next() {
		var i JobAgent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJobAgent = `-- name: UpsertJobAgent :one
INSERT INTO job_agent (id, workspace_id, name, type, config)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET workspace_id = EXCLUDED.workspace_id, name = EXCLUDED.name,
    type = EXCLUDED.type, config = EXCLUDED.config
RETURNING id, workspace_id, name, type, config
`

type UpsertJobAgentParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Type        string
	Config      map[string]any
}

func (q *Queries) UpsertJobAgent(ctx context.Context, arg UpsertJobAgentParams) (JobAgent, error) {
	row := q.db.QueryRow(ctx, upsertJobAgent,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i JobAgent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Config,
	)
	return i, err
}
