// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeploymentVersionStatus string

const (
	DeploymentVersionStatusBuilding DeploymentVersionStatus = "building"
	DeploymentVersionStatusReady    DeploymentVersionStatus = "ready"
	DeploymentVersionStatusFailed   DeploymentVersionStatus = "failed"
	DeploymentVersionStatusRejected DeploymentVersionStatus = "rejected"
	DeploymentVersionStatusPaused   DeploymentVersionStatus = "paused"
)

func (e *DeploymentVersionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentVersionStatus(s)
	case string:
		*e = DeploymentVersionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentVersionStatus: %T", src)
	}
	return nil
}

type NullDeploymentVersionStatus struct {
	DeploymentVersionStatus DeploymentVersionStatus
	Valid                   bool // Valid is true if DeploymentVersionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentVersionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentVersionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentVersionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentVersionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentVersionStatus), nil
}

type ChangelogEntry struct {
	WorkspaceID uuid.UUID
	EntityType  string
	EntityID    string
	EntityData  []byte
	CreatedAt   pgtype.Timestamptz
}

type DeploymentVersion struct {
	ID             uuid.UUID
	Name           string
	Tag            string
	Config         map[string]any
	JobAgentConfig map[string]any
	DeploymentID   uuid.UUID
	Metadata       map[string]string
	Status         DeploymentVersionStatus
	Message        pgtype.Text
	CreatedAt      pgtype.Timestamptz
	WorkspaceID    uuid.UUID
}

type Resource struct {
	ID          uuid.UUID
	Version     string
	Name        string
	Kind        string
	Identifier  string
	ProviderID  uuid.UUID
	WorkspaceID uuid.UUID
	Config      []byte
	CreatedAt   pgtype.Timestamptz
	Metadata    []byte
}

type System struct {
	ID          uuid.UUID
	Name        string
	Description string
	WorkspaceID uuid.UUID
	Metadata    []byte
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}
