// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_validation.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentVersionForPlanTarget = `-- name: GetCurrentVersionForPlanTarget :one
SELECT dv.id, dv.name, dv.tag, dv.config, dv.job_agent_config, dv.deployment_id, dv.metadata, dv.status, dv.message, dv.created_at, dv.workspace_id
FROM deployment_plan_target t
JOIN release rel ON rel.id = t.current_release_id
JOIN deployment_version dv ON dv.id = rel.version_id
WHERE t.id = $1
`

func (q *Queries) GetCurrentVersionForPlanTarget(ctx context.Context, id uuid.UUID) (DeploymentVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentVersionForPlanTarget, id)
	var i DeploymentVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.Config,
		&i.JobAgentConfig,
		&i.DeploymentID,
		&i.Metadata,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listPlanValidationOpaRulesForWorkspace = `-- name: ListPlanValidationOpaRulesForWorkspace :many
SELECT
  r.id,
  r.policy_id,
  r.name,
  r.description,
  r.rego,
  r.created_at,
  p.selector AS policy_selector
FROM policy_rule_plan_validation_opa r
JOIN policy p ON p.id = r.policy_id
WHERE p.workspace_id = $1
  AND p.enabled = true
ORDER BY p.priority DESC, r.created_at DESC
`

type ListPlanValidationOpaRulesForWorkspaceRow struct {
	ID             uuid.UUID
	PolicyID       uuid.UUID
	Name           string
	Description    pgtype.Text
	Rego           string
	CreatedAt      pgtype.Timestamptz
	PolicySelector string
}

func (q *Queries) ListPlanValidationOpaRulesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListPlanValidationOpaRulesForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listPlanValidationOpaRulesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanValidationOpaRulesForWorkspaceRow
	for rows.Next() {
		var i ListPlanValidationOpaRulesForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Name,
			&i.Description,
			&i.Rego,
			&i.CreatedAt,
			&i.PolicySelector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlanValidationResult = `-- name: UpsertPlanValidationResult :exec
INSERT INTO deployment_plan_target_result_validation (
  result_id, rule_id, passed, violations, evaluated_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  NOW()
)
ON CONFLICT (result_id, rule_id) DO UPDATE
SET passed = EXCLUDED.passed,
    violations = EXCLUDED.violations,
    evaluated_at = EXCLUDED.evaluated_at
`

type UpsertPlanValidationResultParams struct {
	ResultID   uuid.UUID
	RuleID     uuid.UUID
	Passed     bool
	Violations []byte
}

func (q *Queries) UpsertPlanValidationResult(ctx context.Context, arg UpsertPlanValidationResultParams) error {
	_, err := q.db.Exec(ctx, upsertPlanValidationResult,
		arg.ResultID,
		arg.RuleID,
		arg.Passed,
		arg.Violations,
	)
	return err
}
