// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policy_skips.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listPolicySkipsForTarget = `-- name: ListPolicySkipsForTarget :many
SELECT id, created_at, created_by, environment_id, expires_at, reason, resource_id, rule_id, version_id
FROM policy_skip
WHERE version_id = $1
  AND (environment_id IS NULL OR environment_id = $2)
  AND (resource_id IS NULL OR resource_id = $3)
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at ASC
`

type ListPolicySkipsForTargetParams struct {
	VersionID     uuid.UUID
	EnvironmentID uuid.UUID
	ResourceID    uuid.UUID
}

func (q *Queries) ListPolicySkipsForTarget(ctx context.Context, arg ListPolicySkipsForTargetParams) ([]PolicySkip, error) {
	rows, err := q.db.Query(ctx, listPolicySkipsForTarget, arg.VersionID, arg.EnvironmentID, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicySkip
	for rows.Next() {
		var i PolicySkip
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.EnvironmentID,
			&i.ExpiresAt,
			&i.Reason,
			&i.ResourceID,
			&i.RuleID,
			&i.VersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
