// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: release_targets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listCurrentVersionsByDeploymentID = `-- name: ListCurrentVersionsByDeploymentID :many
SELECT DISTINCT ON (rel.resource_id, rel.environment_id, rel.deployment_id)
  rel.resource_id,
  rel.environment_id,
  rel.deployment_id,
  dv.id AS version_id,
  dv.name AS version_name,
  dv.tag AS version_tag
FROM release rel
INNER JOIN release_job rj
  ON rel.id = rj.release_id
INNER JOIN job j
  ON rj.job_id = j.id
  AND j.status = 'successful'
INNER JOIN deployment_version dv
  ON rel.version_id = dv.id
WHERE rel.deployment_id = $1
ORDER BY rel.resource_id, rel.environment_id, rel.deployment_id, j.completed_at DESC NULLS LAST
`

type ListCurrentVersionsByDeploymentIDRow struct {
	ResourceID    uuid.UUID
	EnvironmentID uuid.UUID
	DeploymentID  uuid.UUID
	VersionID     uuid.UUID
	VersionName   string
	VersionTag    string
}

func (q *Queries) ListCurrentVersionsByDeploymentID(ctx context.Context, deploymentID uuid.UUID) ([]ListCurrentVersionsByDeploymentIDRow, error) {
	rows, err := q.db.Query(ctx, listCurrentVersionsByDeploymentID, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentVersionsByDeploymentIDRow
	for rows.Next() {
		var i ListCurrentVersionsByDeploymentIDRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.EnvironmentID,
			&i.DeploymentID,
			&i.VersionID,
			&i.VersionName,
			&i.VersionTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestJobsByDeploymentID = `-- name: ListLatestJobsByDeploymentID :many
SELECT DISTINCT ON (rel.resource_id, rel.environment_id, rel.deployment_id)
  rel.resource_id,
  rel.environment_id,
  rel.deployment_id,
  j.id AS job_id,
  j.status AS job_status,
  j.message AS job_message,
  j.created_at AS job_created_at,
  j.completed_at AS job_completed_at,
  COALESCE(
    (SELECT json_object_agg(m.key, m.value)
     FROM job_metadata m WHERE m.job_id = j.id),
    '{}'
  )::jsonb AS job_metadata
FROM release rel
INNER JOIN release_job rj
  ON rel.id = rj.release_id
INNER JOIN job j
  ON rj.job_id = j.id
WHERE rel.deployment_id = $1
ORDER BY rel.resource_id, rel.environment_id, rel.deployment_id, j.created_at DESC
`

type ListLatestJobsByDeploymentIDRow struct {
	ResourceID     uuid.UUID
	EnvironmentID  uuid.UUID
	DeploymentID   uuid.UUID
	JobID          uuid.UUID
	JobStatus      JobStatus
	JobMessage     pgtype.Text
	JobCreatedAt   pgtype.Timestamptz
	JobCompletedAt pgtype.Timestamptz
	JobMetadata    []byte
}

func (q *Queries) ListLatestJobsByDeploymentID(ctx context.Context, deploymentID uuid.UUID) ([]ListLatestJobsByDeploymentIDRow, error) {
	rows, err := q.db.Query(ctx, listLatestJobsByDeploymentID, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestJobsByDeploymentIDRow
	for rows.Next() {
		var i ListLatestJobsByDeploymentIDRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.EnvironmentID,
			&i.DeploymentID,
			&i.JobID,
			&i.JobStatus,
			&i.JobMessage,
			&i.JobCreatedAt,
			&i.JobCompletedAt,
			&i.JobMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseTargetsByDeploymentID = `-- name: ListReleaseTargetsByDeploymentID :many
SELECT DISTINCT ON (d.id, r.id, e.id)
  d.id AS deployment_id,
  r.id AS resource_id,
  r.name AS resource_name,
  r.version AS resource_version,
  r.kind AS resource_kind,
  r.identifier AS resource_identifier,
  e.id AS environment_id,
  e.name AS environment_name,
  dv.id AS desired_version_id,
  dv.name AS desired_version_name,
  dv.tag AS desired_version_tag
FROM computed_deployment_resource cdr
INNER JOIN deployment d
  ON cdr.deployment_id = d.id
INNER JOIN resource r
  ON cdr.resource_id = r.id
INNER JOIN system_deployment sd
  ON cdr.deployment_id = sd.deployment_id
INNER JOIN system_environment se
  ON sd.system_id = se.system_id
INNER JOIN environment e
  ON se.environment_id = e.id
INNER JOIN computed_environment_resource cer
  ON cer.environment_id = e.id
  AND cer.resource_id = r.id
LEFT JOIN release_target_desired_release rtdr
  ON rtdr.deployment_id = d.id
  AND rtdr.resource_id = r.id
  AND rtdr.environment_id = e.id
LEFT JOIN release rel
  ON rtdr.desired_release_id = rel.id
LEFT JOIN deployment_version dv
  ON rel.version_id = dv.id
WHERE d.id = $1
ORDER BY d.id, r.id, e.id
`

type ListReleaseTargetsByDeploymentIDRow struct {
	DeploymentID       uuid.UUID
	ResourceID         uuid.UUID
	ResourceName       string
	ResourceVersion    string
	ResourceKind       string
	ResourceIdentifier string
	EnvironmentID      uuid.UUID
	EnvironmentName    string
	DesiredVersionID   uuid.UUID
	DesiredVersionName pgtype.Text
	DesiredVersionTag  pgtype.Text
}

func (q *Queries) ListReleaseTargetsByDeploymentID(ctx context.Context, id uuid.UUID) ([]ListReleaseTargetsByDeploymentIDRow, error) {
	rows, err := q.db.Query(ctx, listReleaseTargetsByDeploymentID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleaseTargetsByDeploymentIDRow
	for rows.Next() {
		var i ListReleaseTargetsByDeploymentIDRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ResourceID,
			&i.ResourceName,
			&i.ResourceVersion,
			&i.ResourceKind,
			&i.ResourceIdentifier,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.DesiredVersionID,
			&i.DesiredVersionName,
			&i.DesiredVersionTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationMetricsByJobIDs = `-- name: ListVerificationMetricsByJobIDs :many
SELECT
  jvm.id AS metric_id,
  jvm.job_id AS metric_job_id,
  jvm.policy_rule_verification_metric_id AS metric_policy_rule_id,
  jvm.name AS metric_name,
  jvm.provider AS metric_provider,
  jvm.count AS metric_count,
  jvm.success_condition AS metric_success_condition,
  jvm.success_threshold AS metric_success_threshold,
  jvm.failure_condition AS metric_failure_condition,
  jvm.failure_threshold AS metric_failure_threshold
FROM job_verification_metric jvm
WHERE jvm.job_id = ANY($1::uuid[])
ORDER BY jvm.job_id, jvm.id
`

type ListVerificationMetricsByJobIDsRow struct {
	MetricID               uuid.UUID
	MetricJobID            uuid.UUID
	MetricPolicyRuleID     uuid.UUID
	MetricName             string
	MetricProvider         []byte
	MetricCount            int32
	MetricSuccessCondition string
	MetricSuccessThreshold pgtype.Int4
	MetricFailureCondition pgtype.Text
	MetricFailureThreshold pgtype.Int4
}

func (q *Queries) ListVerificationMetricsByJobIDs(ctx context.Context, jobIds []uuid.UUID) ([]ListVerificationMetricsByJobIDsRow, error) {
	rows, err := q.db.Query(ctx, listVerificationMetricsByJobIDs, jobIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationMetricsByJobIDsRow
	for rows.Next() {
		var i ListVerificationMetricsByJobIDsRow
		if err := rows.Scan(
			&i.MetricID,
			&i.MetricJobID,
			&i.MetricPolicyRuleID,
			&i.MetricName,
			&i.MetricProvider,
			&i.MetricCount,
			&i.MetricSuccessCondition,
			&i.MetricSuccessThreshold,
			&i.MetricFailureCondition,
			&i.MetricFailureThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
