// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secret_providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSecretProviderByName = `-- name: GetSecretProviderByName :one
SELECT id, workspace_id, name, type, config, created_at, updated_at
FROM secret_provider
WHERE workspace_id = $1 AND name = $2
`

type GetSecretProviderByNameParams struct {
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) GetSecretProviderByName(ctx context.Context, arg GetSecretProviderByNameParams) (SecretProvider, error) {
	row := q.db.QueryRow(ctx, getSecretProviderByName, arg.WorkspaceID, arg.Name)
	var i SecretProvider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecretProvidersByWorkspaceID = `-- name: ListSecretProvidersByWorkspaceID :many
SELECT id, workspace_id, name, type, config, created_at, updated_at
FROM secret_provider
WHERE workspace_id = $1
ORDER BY name
`

func (q *Queries) ListSecretProvidersByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]SecretProvider, error) {
	rows, err := q.db.Query(ctx, listSecretProvidersByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretProvider
	for rows.Next() {
		var i SecretProvider
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
