// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listWorkspaceIDs = `-- name: ListWorkspaceIDs :many
SELECT id FROM workspace
`

func (q *Queries) ListWorkspaceIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workspaceExists = `-- name: WorkspaceExists :one
SELECT EXISTS(SELECT 1 FROM workspace WHERE id = $1) AS exists
`

func (q *Queries) WorkspaceExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
