// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: release_targets.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReleaseTargetService_Compute_FullMethodName = "/workspace.ReleaseTargetService/Compute"
)

// ReleaseTargetServiceClient is the client API for ReleaseTargetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReleaseTargetServiceClient interface {
	Compute(ctx context.Context, in *ComputeReleaseTargetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReleaseTarget], error)
}

type releaseTargetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReleaseTargetServiceClient(cc grpc.ClientConnInterface) ReleaseTargetServiceClient {
	return &releaseTargetServiceClient{cc}
}

func (c *releaseTargetServiceClient) Compute(ctx context.Context, in *ComputeReleaseTargetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReleaseTarget], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReleaseTargetService_ServiceDesc.Streams[0], ReleaseTargetService_Compute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComputeReleaseTargetsRequest, ReleaseTarget]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReleaseTargetService_ComputeClient = grpc.ServerStreamingClient[ReleaseTarget]

// ReleaseTargetServiceServer is the server API for ReleaseTargetService service.
// All implementations must embed UnimplementedReleaseTargetServiceServer
// for forward compatibility.
type ReleaseTargetServiceServer interface {
	Compute(*ComputeReleaseTargetsRequest, grpc.ServerStreamingServer[ReleaseTarget]) error
	mustEmbedUnimplementedReleaseTargetServiceServer()
}

// UnimplementedReleaseTargetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReleaseTargetServiceServer struct{}

func (UnimplementedReleaseTargetServiceServer) Compute(*ComputeReleaseTargetsRequest, grpc.ServerStreamingServer[ReleaseTarget]) error {
	return status.Errorf(codes.Unimplemented, "method Compute not implemented")
}
func (UnimplementedReleaseTargetServiceServer) mustEmbedUnimplementedReleaseTargetServiceServer() {}
func (UnimplementedReleaseTargetServiceServer) testEmbeddedByValue()                              {}

// UnsafeReleaseTargetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReleaseTargetServiceServer will
// result in compilation errors.
type UnsafeReleaseTargetServiceServer interface {
	mustEmbedUnimplementedReleaseTargetServiceServer()
}

func RegisterReleaseTargetServiceServer(s grpc.ServiceRegistrar, srv ReleaseTargetServiceServer) {
	// If the following call pancis, it indicates UnimplementedReleaseTargetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReleaseTargetService_ServiceDesc, srv)
}

func _ReleaseTargetService_Compute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ComputeReleaseTargetsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReleaseTargetServiceServer).Compute(m, &grpc.GenericServerStream[ComputeReleaseTargetsRequest, ReleaseTarget]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReleaseTargetService_ComputeServer = grpc.ServerStreamingServer[ReleaseTarget]

// ReleaseTargetService_ServiceDesc is the grpc.ServiceDesc for ReleaseTargetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReleaseTargetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.ReleaseTargetService",
	HandlerType: (*ReleaseTargetServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Compute",
			Handler:       _ReleaseTargetService_Compute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "release_targets.proto",
}
