apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctrlplane.chart" . }}-connections
  labels:
    {{- include "ctrlplane.labels" . | nindent 4 }}
data:
  POSTGRES_URL: {{ include "ctrlplane.postgresqlUrl" . | b64enc }}
  REDIS_URL: {{ include "ctrlplane.redisUrl" . | b64enc }}