name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm -F e2e exec playwright install chromium --with-deps

      - name: Start services
        run: pnpm dev &
        env:
          NODE_ENV: test

      - name: Wait for services to start
        run: sleep 30

      - name: Run auth setup
        run: cd e2e && pnpm exec playwright test tests/auth.setup.ts
        env:
          CI: true

      - name: Run API token setup
        run: cd e2e && pnpm exec playwright test tests/api.setup.ts
        env:
          CI: true

      - name: Run API tests
        run: cd e2e && pnpm exec playwright test tests/api
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30 