name: Apps / Pty Proxy

on:
  pull_request:
    branches: ["*"]
    paths:
      - apps/pty-proxy/**
      - packages/db/**
      - packages/logger/**
      - packages/job-dispatch/**
      - packages/auth/**
      - packages/validators/**
      - .github/workflows/apps-pty-proxy.yaml
      - pnpm-lock.yaml
  push:
    branches: ["main"]
    paths:
      - apps/pty-proxy/**
      - packages/db/**
      - packages/logger/**
      - packages/job-dispatch/**
      - packages/validators/**
      - packages/auth/**
      - .github/workflows/apps-pty-proxy.yaml
      - pnpm-lock.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        platform: [linux/amd64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check if Docker Hub secrets are available
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_LOGIN=false" >> $GITHUB_ENV
          else
            echo "DOCKERHUB_LOGIN=true" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: env.DOCKERHUB_LOGIN == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ctrlplane/pty-proxy
          tags: |
            type=sha,format=short,prefix=

      - name: Build
        uses: docker/build-push-action@v6
        if: github.ref != 'refs/heads/main'
        with:
          push: false
          file: apps/pty-proxy/Dockerfile
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main' && env.DOCKERHUB_LOGIN == 'true'
        with:
          push: true
          file: apps/pty-proxy/Dockerfile
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
