name: Apps / Event Worker

on:
  pull_request:
    branches: ["*"]
    paths:
      - apps/event-worker/**
      - packages/db/**
      - packages/job-dispatch/**
      - packages/validators/**
      - .github/workflows/apps-event-worker.yaml
      - pnpm-lock.yaml
  push:
    branches: ["main"]
    paths:
      - apps/event-worker/**
      - packages/db/**
      - packages/job-dispatch/**
      - packages/validators/**
      - .github/workflows/apps-event-worker.yaml
      - pnpm-lock.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ctrlplane/event-worker
          tags: |
            type=sha,format=short,prefix=

      - name: Build
        uses: docker/build-push-action@v6
        if: github.ref != 'refs/heads/main'
        with:
          push: false
          file: apps/event-worker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          file: apps/event-worker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
